# ACT 5, ACT 6 & ACT 7 DATA (Shots 243 to 350)

act5_data = [
    ("And then, when the embers faded, they slept.", "Campfire dying down into soft red coals; tribe members lying on soft furs.", "campfire coals fading to dark red as figures curl up in soft furs around stones"),
    ("And sleep itself worked completely differently than it does today.", "A gentle crescent moon rising above sleeping prehistoric camp.", "slender white crescent moon shining gently over sleeping tribe under open sky"),
    ("If you wake up at three AM right now, you feel instant dread.", "Modern stick figure sitting bolt upright in bed, eyes wide with panic.", "modern stick figure sitting up in bed in pitch black room with eyes wide in panic"),
    ("You check your phone: 03:14 AM.", "Glowing digital alarm clock showing **03:14** in harsh blue digits.", "digital alarm clock glowing 03:14 in bright electric blue across dark bedroom"),
    ("You calculate: 'If I fall asleep in twenty minutes, I get three hours.'", "Mathematical equations floating over stressed modern person's head.", "frustrated stick figure holding head as countdown clock shows 3 hours remaining"),
    ("You toss, turn, stress, and feel like a broken machine.", "Stick figure tangled in bedsheets, punching pillow with frustration.", "tangled stick figure kicking bedsheets with angry squiggly frustration lines"),
    ("You think you have insomnia.", "A prescription pill bottle on modern nightstand labeled 'SLEEP AID'.", "prescription pill bottle on modern nightstand with water glass"),
    ("You don't have insomnia. You have an alarm clock.", "Alarm clock ringing aggressively next to a sleeping stick figure.", "cartoon alarm clock jumping up and down ringing with harsh jagged soundwaves"),
    ("For thousands of years, humans practiced biphasic sleep.", "Antique book page showing woodcut illustration of people waking at midnight.", "vintage woodcut illustration of 16th century peasants waking calmly by candlelight"),
    ("Historical records and modern circadian laboratory trials show", "Laboratory technician observing circadian sleep monitor in sleep clinic.", "sleep research lab monitor showing natural two-wave brainwave sleep cycles"),
    ("that without artificial light, humans sleep in two four-hour blocks.", "Two curved sleep graph waves labeled: 'First Sleep' and 'Second Sleep'.", "two smooth wave graphs on timeline labeled First Sleep and Second Sleep"),
    ("You fell asleep around eight or nine as darkness fell.", "Ancient hunter curling up under furs as twilight turns to deep night.", "hunter curling up peacefully under thick fur blanket as darkness settles"),
    ("Then, naturally, four hours later, your body would wake up.", "Hunter opening eyes smoothly and comfortably around midnight, feeling refreshed.", "hunter opening eyes smoothly without alarm clock feeling relaxed in moonlit tent"),
    ("Around one in the morning, the camp entered 'the watch.'", "Soft moonlight illuminating the camp; two figures sitting quietly by stones.", "gentle blue moonlight illuminating peaceful quiet camp with two awake figures"),
    ("It wasn't a time of panic or racing thoughts.", "Hunter taking a slow deep breath, looking up at the silver Milky Way.", "calm stick figure taking deep breath looking up at brilliant silver Milky Way"),
    ("It was a tranquil, meditative sixty to ninety minutes.", "Stick figure adding two dry branches to coals, tiny sparks fluttering.", "gentle hands placing two dry sticks on embers watching small golden flame lick wood"),
    ("People got up, checked on the embers, and had a sip of water.", "Hunter kneeling to drink fresh cold water from clean river skin bag.", "hunter taking slow refreshing sip of water from leather canteen under stars"),
    ("They chatted in soft whispers with a partner.", "Two stick figures sitting back to back in moonlight, talking quietly.", "two stick figures sitting back to back under blanket whispering quietly together"),
    ("They prayed, meditated, or watched the silent constellations move.", "Silhouettes of trees framing shooting star streaking across night sky.", "shooting star streaking across deep velvet sky framed by quiet tree branches"),
    ("The brain in this midnight waking state produces prolactin,", "Brain diagram showing release of calming prolactin and oxytocin hormones.", "stylized brain cross-section glowing with soft calming blue hormonal light"),
    ("a hormone that produces feelings of calm, peace, and serenity.", "A gentle glowing lotus or light wave floating above the relaxed hunter.", "peaceful stick figure with closed eyes surrounded by soft radiant calm aura"),
    ("Then, after an hour of quiet consciousness,", "Hunter yawning softly and crawling back under warm reindeer hides.", "hunter yawning contentedly and pulling furry blanket back over shoulders"),
    ("they slipped effortlessly into their 'second sleep'", "Hunter fast asleep with peaceful resting face as dawn stars fade.", "hunter sleeping deeply with peaceful smile as night sky turns soft dark blue"),
    ("and woke with the morning sun.", "First golden ray of sunlight hitting the tent opening, waking the birds.", "first ray of golden morning sun entering shelter opening illuminating smiling face"),
    ("We destroyed that rhythm.", "A modern city skyline blazing with millions of harsh electric office lights.", "modern glass skyscraper city glowing with thousands of blinding electric lights"),
    ("We made sleep an eight-hour sprint against an alarm,", "Stick figure running on treadmill attached to giant clock face.", "stick figure running frantically on treadmill inside giant ticking clock"),
    ("and when our ancient biology wakes up in the middle of the night,", "Stick figure staring wide-eyed at bedroom ceiling under streetlamp glare.", "stick figure staring at ceiling illuminated by harsh orange streetlamp light"),
    ("we pathologize it and call it a disease.", "Doctor scribble pad with word 'INSOMNIA' circled in red pen.", "medical clipboard with word INSOMNIA circled with red marker pen"),
    ("It's not a disease. It's your ancient body remembering who you are.", "Hunter silhouette standing under starry sky, breathing deeply in silence.", "silhouette of ancient hunter standing in quiet wilderness under million stars")
]

act6_data = [
    ("Which brings us to the great catastrophe of human history.", "Dramatic dark clouds gathering over open grasslands.", "dramatic dark storm clouds gathering over peaceful golden savannah landscape"),
    ("If foraging was healthier, freer, and full of leisure...", "Hunter skipping stones across river with happy stick figure family.", "joyful scene of hunter family relaxing and laughing by sunny riverbank"),
    ("why on earth did we ever give it up?", "A giant question mark rising above a freshly plowed wheat furrow.", "large hand-drawn question mark planted in muddy agricultural plowed furrow"),
    ("Why trade fifteen hours of play for fifty hours of back-breaking toil?", "Side-by-side: hunter with spear under tree vs farmer collapsed over plow.", "side-by-side: hunter whistling with spear vs farmer collapsed exhausted over plow"),
    ("The answer is: nobody ever decided to give it up.", "A large ancient wooden gate swinging open slowly on its hinges.", "heavy rustic wooden gate swinging open slowly into muddy fenced pen"),
    ("Humanity didn't choose farming. Humanity fell into a trap.", "A crude wooden deadfall animal trap with trigger stick set over bait.", "hand-drawn primitive deadfall trigger trap made of heavy log and stick"),
    ("A trap so slow and subtle that no single generation noticed it closing.", "An hourglass with grains of sand falling slowly one by one.", "hourglass with sand falling one grain at a time into deep accumulating pile"),
    ("It began roughly twelve thousand years ago in the Fertile Crescent.", "Map of Middle East showing wild wheat and barley grasses growing on hillsides.", "map of Fertile Crescent with wild wheat grasses growing across rolling green hills"),
    ("The climate became volatile, with colder droughts and dry spells.", "Sun beating down on cracked dry riverbed with withered wild bushes.", "cracked dry earth with dead brush showing severe prehistoric drought conditions"),
    ("Some hunter bands noticed that wild cereal grasses—wheat and barley—", "Hand gently brushing fingertips over wild wheat ears growing along river.", "hand gently brushing over ripe wild wheat stalks growing along wet riverbank"),
    ("stored remarkably well through the winter if kept dry.", "Stone pit lined with dry grass filled with harvested grain seeds.", "underground stone storage pit lined with straw filled with clean grain seeds"),
    ("So they started tending wild patches. They watered them.", "Stick figure carrying two clay pots of river water to sprinkle on grass patch.", "stick figure carrying two clay pots of water pouring gently on small grain plot"),
    ("They cleared weeds. They saved the best seeds for next spring.", "Hands carefully picking out large plump seeds from chaff into a clay bowl.", "hands separating fat wheat grains from dry chaff into small terracotta bowl"),
    ("It seemed like an innocent, brilliant life insurance policy.", "Hunter smiling, pointing proudly at small fenced plot of green grain.", "stick figure smiling proudly with hands on hips looking at small garden plot"),
    ("More food security meant fewer winter worries.", "Clay pot filled to brim with grain sitting in cozy winter shelter.", "warm shelter interior with full grain jar sitting safely by small hearth fire"),
    ("But wheat came with a hidden biological trigger.", "Close-up of a single ear of wheat glowing with an ominous subtle red outline.", "single golden wheat stalk isolated on white background with subtle red aura"),
    ("Wild game and tubers require years of breastmilk to digest,", "Mother holding child in forest, child nursing peacefully.", "mother holding child in forest setting with gentle nurturing atmosphere"),
    ("so hunter-gatherer mothers weaned children around age four.", "Growth chart showing forager child weaning at age four mark.", "growth chart showing child weaning timeline reaching age four milestone"),
    ("That kept birth spacing at four to five years naturally.", "Timeline showing one child born every four years on horizontal line.", "timeline diagram with baby icons spaced every four years along timeline"),
    ("Tribe population stayed small and perfectly balanced with the forest.", "Small tribe of 25 people walking across vast untouched wilderness valley.", "small group of 25 stick figures walking peacefully through vast open landscape"),
    ("Wheat porridge changed the math overnight.", "Boiled soft wheat gruel being spooned into baby's open mouth.", "clay spoon feeding soft cooked grain porridge to small infant"),
    ("Cooked starch is easy for infant guts to process.", "Baby happily eating porridge from ceramic bowl.", "smiling baby sitting on mat eating warm porridge with ceramic spoon"),
    ("Mothers could wean babies at age one instead of age four.", "Growth chart dropping dramatically: weaning age moves from 4 down to 1.", "growth chart arrow dropping from age 4 down to age 1 milestone"),
    ("Birth spacing collapsed from four years to eighteen months.", "Timeline showing babies appearing every single year in rapid succession.", "timeline packed tightly with baby icons appearing one after another every year"),
    ("The population exploded.", "Stick figures multiplying across screen: 20 becomes 60, 60 becomes 200.", "crowd diagram showing stick figure population multiplying exponentially")
]

act7_data = [
    ("Within three generations, a band of twenty-five people", "Small quaint camp of five animal skin tents.", "small simple camp of five leather tents by riverbank"),
    ("became a village of three hundred people.", "A crowded mud-brick village with dense houses and narrow muddy alleys.", "crowded ancient mud-brick village with dozens of packed flat-roofed houses"),
    ("And suddenly, the trap snapped shut.", "A wooden deadfall trap crashing down into the dirt with dust puff.", "heavy wooden deadfall trap slamming down hard on ground with dust cloud"),
    ("Three hundred people cannot survive by hunting wild deer in that valley.", "Hunters looking into forest: all deer are gone; empty woods.", "hunters standing in barren forest looking around with empty hands, no game"),
    ("There are not enough wild roots in fifty miles to feed that many mouths.", "Empty foraging basket on dry trampled ground.", "empty woven basket upside down on bare trampled muddy earth"),
    ("You cannot go back to hunting and gathering.", "Stick figure trying to walk toward forest, blocked by a wall of people.", "stick figure trying to walk toward green forest blocked by crowd of hungry villagers"),
    ("If you stop farming for a single season, your children starve.", "Mother looking down worriedly at three hungry children clinging to her skirt.", "worried mother surrounded by three small hungry children crying for food"),
    ("You are trapped.", "Stick figure holding wooden hoe, looking down at soil with heavy posture.", "stick figure standing in field with heavy wooden hoe looking trapped and tired"),
    ("Now you must plow more fields.", "Men straining hard pulling wooden plow through heavy, muddy clay soil.", "two men straining forward pulling heavy wooden plow through thick mud"),
    ("You must clear every tree. You must weed from sunrise to sunset.", "Stick figure on hands and knees pulling stubborn thorny weeds from wheat rows.", "stick figure crawling on knees under scorching sun pulling weeds from wheat field"),
    ("You must dig irrigation ditches and carry water until your arms shake.", "Stick figure carrying heavy water buckets on wooden yoke across shoulders.", "stick figure carrying heavy wooden yoke with two sloshing water buckets"),
    ("And because grain is harvested in one big surge,", "Giant stone granary filled to the roof with dry golden grain sacks.", "massive stone storehouse with doorway showing stacks of grain sacks inside"),
    ("you have to store it in granaries.", "Stick figures carrying heavy baskets of grain up wooden ladder into silo.", "workers climbing wooden ladder carrying heavy grain baskets into tall silo"),
    ("And the moment you have granaries full of food,", "Neighboring bandits with spears watching storehouse greedily from ridge.", "shadowy figures on distant hilltop watching stone granary with greedy eyes"),
    ("other starving villages want to steal it.", "Bandits running toward village waving clubs and torches.", "raiders with clubs and torches charging toward ancient village gate"),
    ("So you need walls. Thick, heavy stone walls.", "Men hauling giant limestone boulders to build high defensive perimeter wall.", "workers lifting heavy stone blocks building high defensive wall around village"),
    ("You need full-time guards to stand watch on those walls.", "Two armed guards with copper spears standing atop stone watchtower.", "two guards standing on battlements of stone city wall holding spears"),
    ("You need administrators to count the grain sacks.", "Scribe sitting cross-legged carving cuneiform numbers on wet clay tablet.", "ancient scribe holding stylus pressing tally marks into wet rectangular clay tablet"),
    ("You need tax collectors to take grain from the farmers to feed the guards.", "Official taking half the grain sack from a weeping farmer family.", "official taking grain sacks from humble farmer family standing outside hut"),
    ("You need a king to organize the army.", "A king sitting on high carved stone throne wearing gold crown, pointing command.", "king sitting on carved stone throne holding royal scepter giving stern orders"),
    ("And just like that, human freedom vanished.", "A heavy iron chain linking from farmer hoe to castle gate.", "stylized chain wrapping around farmer wooden hoe linking to grand stone palace"),
    ("Private property was born. Land was owned. Borders were drawn.", "Map of valley crisscrossed by sharp black fences, walls, and boundary stones.", "map of green valley carved up into rigid geometric parcels with stone walls"),
    ("Human time was no longer your own.", "An ancient stone sundial casting a long sharp shadow across the dirt.", "stone sundial in city square casting sharp dark shadow marking passing hours"),
    ("It belonged to the harvest, the granary, the tax collector, and the king.", "Four icons in a grid: grain sheaf, storehouse, clay tax tablet, royal crown.", "four grid icons: wheat sheaf, locked storehouse, tax clay tablet, royal crown"),
    ("The open horizon was traded away for a muddy field and a fence.", "Farmer leaning on hoe watching distant flock of birds flying free over forest.", "farmer leaning heavily on hoe looking longingly at wild birds soaring free"),
    ("Tonight, you will crawl into your bed.", "Modern bedroom at night; soft lamp light on modern wooden nightstand.", "modern cozy bedroom at night with soft warm lamp illuminating bedside table"),
    ("You will reach over to your phone on the bedside table.", "Hand reaching out from duvet toward glowing smartphone resting on table.", "hand reaching out toward glowing smartphone resting next to water glass"),
    ("You will set that same electronic chime to ring at six-thirty AM.", "Close-up of screen showing alarm toggle sliding green: 'ALARM SET FOR 6:30 AM'.", "close-up of phone screen setting alarm toggle with green checkmark for 6:30 AM"),
    ("You will spend the next thirty or forty years of your life", "Time-lapse montage: stick figure aging from 25 to 65 sitting at office desk.", "time-lapse illustration of stick figure aging at desk hair turning from dark to gray"),
    ("commuting in traffic, sitting in chairs, answering emails,", "Stick figure staring out commuter bus window at grey rainy city street.", "stick figure looking out rain-streaked bus window at grey city buildings"),
    ("paying down a thirty-year mortgage on a box made of drywall,", "Stick figure signing mortgage papers across table from smiling bank officer.", "stick figure signing official mortgage papers across desk from bank officer"),
    ("saving every spare dollar into an index fund,", "Doodle of piggy bank slowly filling with coins over decades.", "glass piggy bank filling with gold coins while calendar pages flip rapidly"),
    ("all so that someday, if your knees and heart still work,", "Elderly modern stick figure walking slowly with a cane along park path.", "elderly modern stick figure with walking cane smiling gently on autumn park bench"),
    ("you can finally retire.", "Bold text card centered on canvas: **RETIREMENT**.", "bold center text banner reading RETIREMENT on clean cream canvas"),
    ("And what is the grand dream of retirement?", "Dream bubble showing someone fishing by river, walking in woods, baking bread.", "dream bubble showing three scenes: fishing at lake, forest hiking, warm kitchen baking"),
    ("To wake up with the sun. To have nowhere you have to be.", "Older stick figure standing on porch with coffee, watching peaceful sunrise.", "older stick figure on wooden cabin porch watching peaceful golden sunrise over lake"),
    ("To walk in the woods with no clock in your pocket.", "Person strolling peacefully down pine needle trail with hands in pockets.", "stick figure strolling along pine forest path with sunbeams shining through branches"),
    ("To cook slow, fresh food with your hands.", "Hands chopping fresh vegetables on wooden cutting board with warm sunlight.", "hands chopping fresh garden vegetables and herbs on rustic wooden board"),
    ("To take long, guilt-free naps in the afternoon shade.", "Stick figure sleeping happily in hammock strung between two shady apple trees.", "stick figure relaxing in hammock strung between two fruit trees in summer breeze"),
    ("To sit around a fire at night with the people you love,", "Old friends sitting around backyard fire pit, laughing and holding mugs.", "group of older friends sitting around cozy stone fire pit in backyard laughing"),
    ("telling stories and looking up at the stars.", "Friends looking up together at brilliant starry sky over dark trees.", "group of friends looking up in awe at glowing stars and Milky Way in clear night sky"),
    ("Do you see the crushing irony?", "Modern stick figure looking in bathroom mirror, staring into own eyes.", "modern stick figure looking into bathroom mirror with deep thoughtful expression"),
    ("You are working forty-five years of your mortal existence", "Chalkboard showing 45 years of office work leading to a small question mark.", "chalkboard timeline showing 45 years of office desks leading to small question mark"),
    ("hoping to buy back the exact life", "Golden glowing silhouette of ancient hunter standing free on mountain ridge.", "golden glowing silhouette of prehistoric hunter standing free on high grassy ridge"),
    ("that your ancestors lived every single day from birth to death.", "Hunter family laughing together around their fire under open ancient sky.", "prehistoric hunter family laughing warmly together around glowing hearth under stars"),
    ("And they would find it very strange that you traded it away for an alarm.", "Final screen: simple alarm clock icon dissolving into smoke on white canvas.", "simple alarm clock doodle fading away into curling wisp of woodsmoke on off-white canvas")
]

