"""
Storyboard Visual Data: Part 3 (Shots 241 - 361)
Project: 2- What Did Ancient Humans Do at Night
"""

SHOTS_PART_3 = [
    # --- ACT 5 CONTINUED: PROLACTIN BLISS & STATE OF CONSCIOUSNESS (241 - 255) ---
    (241, "he found something unbelievable.",
     "Scientist stick figure staring in disbelief at laboratory analyzer with wide eyes",
     "front",
     "high-tech biochemical laboratory with digital printouts and centrifuge",
     "scientist stick figure holding laboratory printout strip with both hands, two wide amazed black dot eyes, mouth agape in astonishing surprise"),

    (242, "Their bodies were pumping out",
     "Stick figure body silhouette with glowing golden aura pumping from endocrine system",
     "front",
     "clean anatomical diagram background with subtle scientific grid",
     "stick figure silhouette with pituitary gland glowing like a tiny sun, pumping radiant golden ripples throughout the bloodstream, two calm black dot eyes"),

    (243, "massive amounts of prolactin -",
     "Large chemical bottle labeled 'PROLACTIN: BLISS HORMONE' overflowing with golden sparks",
     "none",
     "clean laboratory bench with sparkling amber glow",
     "oversized amber laboratory bottle labeled 'PROLACTIN' overflowing with effervescent golden bubbles and glittering starburst doodles"),

    (244, "the exact same bliss hormone",
     "Split-panel doodle: meditating monk on left, smiling embrace on right",
     "none",
     "clean two-panel layout with warm pastel backgrounds",
     "left panel shows a stick figure meditating peacefully on a mountain; right panel shows two stick figures embracing warmly, both filled with golden bliss"),

    (245, "released during meditation",
     "Stick figure sitting serenely in lotus position floating slightly above ground",
     "front",
     "minimalist zen garden background with smooth stones and bamboo stalk",
     "stick figure floating gently two inches above a woven mat in deep meditation, two peaceful closed curved eyes, radiating soft concentric waves"),

    (246, "and after intimacy.",
     "Two stick figures resting side by side smiling contentedly under soft duvet",
     "front",
     "cozy candlelit bedroom with warm shadows and fluffy blankets",
     "two stick figures lying side by side in bed with hands entwined, each with two calm smiling black dot eyes, surrounded by tiny comic heart doodles"),

    (247, "The volunteers described feeling",
     "Volunteer stick figure sitting up in bed speaking with therapist with glowing expression",
     "front",
     "clinical consultation room with comfortable armchair and clipboard",
     "volunteer stick figure sitting in armchair with hands open, expression glowing with serenity, two bright peaceful black dot eyes and gentle smile"),

    (248, "an almost euphoric,",
     "Stick figure floating weightlessly through a field of soft glowing clouds",
     "front",
     "ethereal dreamscape background with drifting pastel clouds and starlight",
     "stick figure floating effortlessly on back with arms outstretched, two serene blissful black dot eyes, bathed in warm golden light"),

    (249, "crystal-clear tranquility.",
     "Close-up of stick figure's face with crystal clarity and peaceful mind waves",
     "front",
     "pristine clear water reflection background with gentle circular ripples",
     "close-up of stick figure head with two sparkling crystal-clear black dot eyes, smooth brow, and absolute tranquil stillness in expression"),

    (250, "It wasn't a sleep disorder at all -",
     "Medical chart with red 'DISORDER' text crossed out with a green stamp",
     "none",
     "clinical clipboard background with diagnostic checklist",
     "medical intake form with 'SLEEP DISORDER / INSOMNIA' crossed out with heavy red lines, stamped with a bold green seal: 'HEALTHY ANCESTRAL BIOLOGY'"),

    (251, "it was a completely unique state",
     "Concentric circles showing three states: Awake, Asleep, and The Midnight Watch",
     "none",
     "clean educational infographic background with elegant circular tiers",
     "three overlapping colored circles: yellow 'Daytime Alertness', dark blue 'Deep Sleep', and central glowing purple 'The Midnight Watch Consciousness'"),

    (252, "of human consciousness",
     "Stylized illustration of human mind glowing like a tranquil jewel in the dark",
     "none",
     "deep cosmic indigo background with subtle neural network lines",
     "stylized human profile contour with a radiant glowing crystal inside the brain, emitting steady, calm ripples of coherent alpha waves"),

    (253, "that our modern world completely",
     "A heavy modern asphalt steamroller driving over a tranquil ancient meadow",
     "none",
     "split landscape: lush wildflower meadow being flattened by grey asphalt",
     "massive yellow industrial steamroller paving a smooth grey highway over blooming ancient wildflowers, comic steam clouds rising"),

    (254, "paved over.",
     "Modern grey concrete sidewalk with a tiny fossil of an ancient campfire underneath",
     "none",
     "cross-section of modern city street showing layers of asphalt and concrete",
     "cross-section showing cold grey sidewalk on top, with a crushed cross-section of ancient campfires and glowing embers buried deep below"),

    # --- ACT 6: THE MODERN ERASURE: STREETLIGHTS, EDISON & BROKEN BIOLOGY (255 - 325) ---
    (255, "So what killed the midnight",
     "Stick figure standing by a chalk outline of a missing bed on the floor",
     "front",
     "detective mystery scene with magnifying glass and crime tape doodles",
     "detective stick figure in trench coat examining a chalk outline of a bed on the floor, two puzzled black dot eyes and scratching head"),

    (256, "chill session?",
     "A cozy cup of midnight tea and book being blown away by a harsh gust of light",
     "none",
     "dark cozy room suddenly invaded by harsh angular white beam of light",
     "cozy bedside mug of tea and open book on nightstand suddenly blasted by a blinding white angular light beam cutting through the darkness"),

    (257, "One word: light.",
     "Dramatic black screen with single giant word 'LIGHT' glowing intensely in white",
     "none",
     "stark black void background with brilliant white central flare",
     "bold minimalist typographic composition: the word 'LIGHT' rendered in massive high-contrast white vector letters glowing with lens flare rays"),

    (258, "In the 1600s,",
     "Historical European city square with 17th-century cobblestones and church tower",
     "none",
     "17th-century European city street at dusk with slate roofs and stone facades",
     "historic urban plaza in the 1600s, showing tall brick merchant houses, horse carriages, and deep evening shadows falling across streets"),

    (259, "European cities started putting",
     "City workers erecting the very first iron street lamp post on a corner",
     "side",
     "cobblestone street corner with brick townhouse wall",
     "two workman stick figures in side profile carrying a tall wrought-iron lantern post, single focused black dot eye on each, positioning it upright"),

    (260, "up public street lamps.",
     "Ornate wrought-iron gas street lamp glowing against the dark brick wall",
     "none",
     "dark textured brick wall with antique iron lamp bracket",
     "ornate black iron street lantern with glass panes, housing a flickering yellow flame casting a clean cone of yellow light onto cobblestones"),

    (261, "Paris did it under King Louis",
     "Ornate portrait of King Louis XIV in royal velvet ermine robe and oversized wig",
     "front",
     "Versailles palace room with gilded mirrors and golden fleur-de-lis wallpaper",
     "King Louis XIV stick figure wearing a towering curly black powdered wig, ermine fur cape, and royal crown, two regal proud black dot eyes"),

    (262, "the Fourteenth to stop muggings,",
     "Cartoon thief stick figure in mask running away in shock as street lamp turns on",
     "side",
     "cobblestone alleyway with sudden bright circle of streetlight",
     "cloaked cartoon thief stick figure with mask in side profile dropping sack of loot, startled single wide black dot eye, fleeing the light beam"),

    (263, "and London quickly copied them.",
     "London street scene with Big Ben in background and row of new streetlights",
     "none",
     "London cityscape along the River Thames with silhouette of Westminster",
     "row of gleaming Victorian gas street lamps illuminating London bridge, casting bright yellow reflection ribbons across the dark water"),

    (264, "The night,",
     "Dark shadowy medieval city street that once looked terrifying and treacherous",
     "none",
     "narrow medieval European alley with dark overhangs and mysterious shadows",
     "atmospheric shot of a narrow medieval alleyway shrouded in spooky deep charcoal darkness, showing how intimidating night once was"),

    (265, "which had been terrifying for millennia,",
     "Stick figure trembling in fear hugging a wooden doorway in pitch-black ancient street",
     "front",
     "dark ancient village lane with stormy night sky and menacing shadows",
     "medieval stick figure pressed against wooden door frame, knees knocking with vibration lines, two wide terrified black dot eyes and teeth chattering"),

    (266, "suddenly became walkable.",
     "Stick figure couple strolling leisurely down illuminated cobblestone boulevard",
     "side",
     "charming lit city street with warm glowing shop windows and lampposts",
     "two stick figures in side profile walking arm-in-arm casually along the sidewalk under lamplight, single happy black dot eye on each"),

    (267, "Then came cheap candles,",
     "Factory production line churning out hundreds of white wax candles",
     "none",
     "early industrial workshop with wooden drying racks and wax vats",
     "neat rows of inexpensive molded tallow and wax candles stacked high on wooden factory tables, with little comic price tags reading '1 PENNY'"),

    (268, "then gas lamps in the 1800s,",
     "Intricate 19th-century municipal gas lamp glowing with bright green-tinted flame",
     "none",
     "Victorian brick street corner with wrought iron lamp post",
     "close-up of a Victorian street gas lantern with brass gas pipe and luminous mantle glowing intensely, casting crisp sharp shadows"),

    (269, "and then in 1879,",
     "Wall calendar turning over to bold historic year '1879' with electric spark doodles",
     "none",
     "vintage workshop background with patent drawings on wall",
     "tear-off calendar block with large bold text 'OCTOBER 1879', surrounded by electric blue zigzag spark doodles and patent blueprint sketches"),

    (270, "Thomas Edison rolled out the",
     "Thomas Edison stick figure in lab coat proudly holding glowing incandescent bulb",
     "front",
     "Menlo Park laboratory with workbench cluttered with glass tubes, wires, and coils",
     "Edison stick figure with messy hair and spectacles, holding up a glowing glass bulb, two brilliant proud black dot eyes and triumphant grin"),

    (271, "commercial light bulb.",
     "Detailed classic Edison light bulb with glowing carbon filament loop",
     "none",
     "dark workshop background with dramatic golden filament illumination",
     "macro illustration of an authentic Edison bulb: teardrop glass envelope, copper screw base, and loop of blazing orange carbon filament glowing brightly"),

    (272, "Within a single generation,",
     "Time-lapse graphic of electric power lines rapidly spreading across a dark city",
     "none",
     "panoramic city skyline view transitioning from dark to illuminated",
     "dynamic comic perspective of telephone and power poles marching into the distance, stringing glowing electric wires that light up entire blocks"),

    (273, "three hundred thousand years of",
     "Infographic showing 300,000 years of night sky being covered by electric bulb net",
     "none",
     "cosmic dark background with grid overlay",
     "vast expanse of pristine dark starry sky being covered by a glowing modern electrical grid net, symbolizing the artificial conquest of night"),

    (274, "natural night were completely erased.",
     "Giant eraser wiping away a dark starry sky to reveal bright artificial yellow",
     "none",
     "split composition: starry night on right, bright artificial yellow on left",
     "humorous giant rubber eraser doodle physically wiping away the stars and darkness, leaving behind flat sterile electric yellow background"),

    (275, "Even the word 'curfew' gives it away.",
     "Vintage antique dictionary entry highlighting the word 'CURFEW' with magnifying glass",
     "none",
     "aged leather lexicon page with crisp printed serif typography",
     "enlarged dictionary page with red bracket around entry: CURFEW n. [fr. Old French couvre-feu], adjacent to an illustrated bell tower"),

    (276, "It comes from the medieval",
     "Medieval French town square with gothic church and cobblestones",
     "none",
     "14th-century French medieval town with timber-framed houses and cathedral",
     "quaint historic French village at dusk with stone well in center, timbered walls, and evening shadows lengthening across the square"),

    (277, "French 'couvre-feu,",
     "Medieval French manuscript page displaying the illuminated phrase 'Couvre-Feu'",
     "none",
     "illuminated vellum manuscript with red and gold foil leaf borders",
     "magnificent medieval gothic calligraphy displaying 'Couvre-Feu' in dark ink with ornate vine borders and painted miniature of a hearth"),

    (278, "' which literally means 'cover",
     "Hands using metal bell-shaped hearth lid to cover a burning domestic hearth",
     "none",
     "rustic stone fireplace with glowing wood embers inside",
     "detailed illustration of a traditional brass bell-shaped 'couvre-feu' dome being placed directly over glowing hearth coals to smother them"),

    (279, "the fire.' In old towns,",
     "Medieval town watchman ringing a large church curfew bell in tower",
     "side",
     "stone bellfry tower overlooking sleeping medieval town at twilight",
     "watchman stick figure in side profile in woolen tunic pulling heavy hemp rope, single focused black dot eye, church bell swinging dynamically"),

    (280, "an evening bell would ring",
     "Massive bronze church bell swinging vigorously with comic 'CLANG!' soundwaves",
     "none",
     "stone belfry arched window open to twilight sky",
     "giant bronze bell swinging high in tower with radiating concentric soundwaves and bold comic lettering: 'CLANG! DONG!'"),

    (281, "telling everyone to smother",
     "Medieval stick figure in nightshirt putting metal lid over hearth embers",
     "side",
     "stone cottage interior at night with family bed in corner",
     "stick figure in side profile placing a brass cover over the fireplace embers, single sleepy black dot eye, wisps of smoke dying down"),

    (282, "their hearths,",
     "Dark hearth completely covered with iron lid, zero light escaping into room",
     "none",
     "rustic stone hearth in total darkness with cool ashes",
     "close-up of the metal cover sealed tightly over the fireplace floor, plunging the entire cottage room into natural dark shadows"),

    (283, "because night was supposed to be dark,",
     "Cozy cottage bedroom in total natural darkness with peaceful moonlight through shutter",
     "none",
     "cottage bedroom interior with wooden shutters slightly ajar",
     "peaceful bedroom completely immersed in cool, gentle natural night darkness, with a single silver beam of moonlight resting on the floorboards"),

    (284, "dangerous,",
     "Dark medieval alleyway with spooky shadows and glowing predator eyes in background",
     "none",
     "creepy medieval alley with hanging shop signs creaking in the wind",
     "spooky cobbled lane with deep pitch-black doorways, a stray black cat arching its back, and mysterious eyes lurking in the gloom"),

    (285, "and strictly meant for sleeping.",
     "Medieval family of stick figures tucked asleep in large wooden bed under quilts",
     "front",
     "cozy cottage bedroom with timber ceiling beams and sleeping cat on rug",
     "three stick figures sleeping peacefully in a wide wooden bed, all with two gentle sleeping dash eyes, quilts tucked under chins"),

    (286, "In fact,",
     "Town guard holding halberd and lantern standing under stone archway",
     "front",
     "medieval stone city gate under dark midnight sky",
     "stern medieval town guard stick figure in iron helmet holding a polearm halberd, two stern watchful black dot eyes and scowling mustache doodle"),

    (287, "walking around a medieval city",
     "Stick figure walking stealthily down a dark empty street looking nervous",
     "side",
     "narrow cobblestone street at midnight with closed wooden shutters",
     "stick figure in side profile tiptoeing down the middle of the street looking over shoulder, single nervous black dot eye and biting lip"),

    (288, "after dark without holding a",
     "Empty hand raised looking down with realization that lantern is missing",
     "none",
     "dark city street corner with stone paving",
     "close-up of a stick figure hand held open in the darkness with zero lantern, surrounded by comic red alarm exclamation marks"),

    (289, "lantern was straight-up illegal.",
     "Medieval royal proclamation scroll stamped with bold red 'ILLEGAL' seal",
     "none",
     "stone wall with nailed parchment decree",
     "official parchment decree nailed to stone pillar stating: 'No person shall walk after curfew without light upon pain of imprisonment', stamped red"),

    (290, "Night belonged to outlaws,",
     "Silhouette of highwayman stick figure with mask and cloak lurking behind corner",
     "side",
     "dark medieval street corner with brick archway",
     "sneaky bandit stick figure in cape and feathered tricorn hat in side profile peering around corner, single mischievous glowing black dot eye"),

    (291, "predators,",
     "Shadowy wolf stalking along the edge of a medieval village fence",
     "side",
     "outer village boundary with wooden split-rail fence and dark forest edge",
     "sleek black wolf silhouette in side profile slinking along the fence line, single sharp glowing eye focused on the livestock pens"),

    (292, "and creepy ghost stories.",
     "Spooky hand-drawn comic ghost floating above an ancient cemetery wall",
     "front",
     "old stone graveyard at midnight with crooked headstones under full moon",
     "whimsical white comic sheet ghost floating above headstones, two hollow cartoon black dot eyes, with a funny spooky expression"),

    (293, "So naturally,",
     "Stick figure inventor in top hat with ambitious blueprint for electric city",
     "front",
     "19th-century drafting studio with rolled blueprints and brass tools",
     "proud inventor stick figure in Victorian vest and top hat, holding rolled architectural plans, two ambitious energetic black dot eyes and confident smirk"),

    (294, "humans decided to conquer it.",
     "Stick figure planting a flag labeled 'PROGRESS' atop a defeated dark mountain of night",
     "front",
     "monumental cliff overlooking a blazing illuminated modern metropolis",
     "triumphant stick figure planting a bold white flag labeled 'LIGHT' atop a conquered mountain peak, two proud heroic black dot eyes"),

    (295, "We flooded the night",
     "City street at night flooded with blazing white light from dozens of bright lamps",
     "none",
     "modern urban downtown street canyon with neon signs and storefronts",
     "vibrant cityscape at midnight bathed in blinding white and yellow electric light, completely obliterating any trace of natural night shadows"),

    (296, "with electric light,",
     "Close-up of bright modern LED stadium floodlight blasting photons into frame",
     "none",
     "deep dark night sky pierced by high-intensity beam",
     "powerful industrial LED light fixture firing brilliant white light rays outward, with comic optical lens flare circles spanning the screen"),

    (297, "patted ourselves on the back,",
     "Two modern stick figures high-fiving under a glaring bright billboard",
     "front",
     "busy modern city sidewalk illuminated like noon day",
     "two modern stick figures giving an enthusiastic high-five beneath a giant glowing LED billboard, both with two self-satisfied smiling black dot eyes"),

    (298, "and called it progress.",
     "Giant golden trophy doodle engraved with the word 'PROGRESS' under bright spotlights",
     "none",
     "clean corporate presentation background with dramatic spotlight beams",
     "ornate golden trophy cup with laurel wreaths engraved with 'PROGRESS', flanked by two blinding halogen worklights, comic sparkle stars"),

    (299, "Except we completely broke our",
     "Cracked biological clock with broken cogs and springs popping out",
     "none",
     "clean parchment background with mechanical debris",
     "hand-drawn internal human body circadian clock with fractured glass face, broken cogs, and loose coils springing outward in comical malfunction"),

    (300, "biology in the process.",
     "Stick figure sitting with head in hands looking exhausted under fluorescent office lights",
     "front",
     "modern sterile office cubicle with harsh white overhead fluorescent tube lights",
     "exhausted stick figure slumped in swivel chair with face in hands, two weary drooping black dot eyes, overwhelmed by the sterile glare"),

    (301, "Today,",
     "Modern stick figure sitting in bed in dark room staring at glowing phone screen",
     "side",
     "dark modern bedroom at night with messy duvet and dark walls",
     "stick figure in side profile sitting hunched in bed, face illuminated by a glaring blue cone of light from smartphone, single hypnotized dot eye"),

    (302, "the average human bathes",
     "Stick figure literally sitting in a bathtub filled with glowing lightbulbs",
     "front",
     "whimsical bathroom background with bathroom tiles and modern fixtures",
     "humorous cartoon stick figure sitting in a porcelain clawfoot bathtub overflowing with hundreds of glowing lightbulbs, two dazed black dot eyes"),

    (303, "in artificial glare for seven to",
     "Clock ticking from 6 PM to 2 AM with a floodlight continuously shining on bed",
     "none",
     "modern bedroom with large wall clock ticking through evening hours",
     "wall clock showing continuous progress from sunset at 6 PM to 2 AM, while a blinding desk lamp stays continuously illuminated"),

    (304, "eight hours after sunset.",
     "Infographic showing 8 extra hours of artificial glare stretching past sundown",
     "none",
     "clean paper infographic chart with sun and bulb icons",
     "horizontal bar chart: sun drops at 6 PM, followed by an eight-hour blazing red bar labeled '8 HOURS ARTIFICIAL BLUE GLARE'"),

    (305, "And the blue light screaming",
     "Cartoon smartphone screen shouting with a megaphone emitting blue sonic waves",
     "none",
     "dark bedroom nightstand with bedside phone",
     "smartphone character with a megaphone physically screaming jagged electric blue soundwaves directly toward the pillow"),

    (306, "from your phone screen actively",
     "Intense electric blue light beam shooting from phone directly into eyeball",
     "none",
     "macro perspective from behind the phone screen",
     "high-energy laser-like cone of piercing blue light firing from the smartphone glass into a comic eyeball graphic, crackling with sparks"),

    (307, "bullies your brain",
     "Cartoon blue light photon wearing boxing gloves punching a sleepy pineal gland",
     "front",
     "stylized anatomical brain interior with comic boxing ring ropes",
     "aggressive cartoon blue light drop with red boxing gloves punching a sleepy, peaceful brain character, who holds up hands in defense"),

    (308, "into shutting down melatonin production.",
     "Melatonin factory inside brain closing its heavy iron blast doors and turning off lights",
     "none",
     "internal brain cross-section with factory building doodle",
     "little factory inside brain labeled 'MELATONIN CORP' slamming down heavy iron metal shutter doors with a 'CLOSED FOR NIGHT' sign"),

    (309, "Your eyeballs can't tell the",
     "Two giant cartoon eyeballs sitting in a courtroom looking utterly confused",
     "front",
     "whimsical courtroom witness stand with wooden gavel",
     "two expressive cartoon eyeballs sitting on a bench, pupil dots looking back and forth in total bewilderment, question marks above"),

    (310, "difference between TikTok",
     "Smartphone screen displaying colorful short-form dancing stick figure video",
     "none",
     "clean modern phone interface with like hearts and comment icons",
     "vertical smartphone display showing a dancing stick figure loop with floating red hearts and colorful UI buttons, glowing with bright luminescence"),

    (311, "and the midday sun.",
     "Blazing golden desert sun wearing sunglasses smiling down from top of screen",
     "none",
     "bright yellow comic sunbeam sky background",
     "hand-drawn blazing yellow sun with bold black outlines, wearing black cool sunglasses, beaming intense radiation rays across the frame"),

    (312, "When high-energy photons slam",
     "High-energy comic blue photon particles flying like laser arrows into retina",
     "none",
     "dark optical diagram cross-section of eye lens and retina",
     "swarm of fast-moving blue comic arrows labeled 'BLUE PHOTONS' slamming into the back wall of the retina with impact spark doodles"),

    (313, "into your retina",
     "Close-up of human retina with nerve cells flashing bright warning sirens",
     "none",
     "clean biological cross-section of rods and cones on retina",
     "delicate microscopic view of retinal nerve cells flashing with bright red comic alarm beacons as intense blue light hits them"),

    (314, "at eleven at night,",
     "Digital bedside clock glowing '11:00 PM' while stick figure lies in bed illuminated",
     "side",
     "dark bedroom at 11:00 PM with nightstand and cold blue ambient illumination",
     "stick figure in side profile in bed holding phone right before midnight, digital clock reading '11:00 PM', single wide awake black dot eye"),

    (315, "your brain thinks,",
     "Cartoon brain character wearing beach sunglasses and Hawaiian floral lei",
     "front",
     "tropical beach dream background with palm tree and surfboard",
     "cartoon brain character sipping a tropical coconut drink through a straw, wearing sunglasses and floral garland, two carefree cheerful eyes"),

    (316, "'Awesome,",
     "Brain character giving enthusiastic double thumbs-up with happy grin",
     "front",
     "clean comic panel background with joyful sunburst",
     "brain character giving two big thumbs up, two energetic happy black dot eyes and wide grinning mouth, totally convinced it is daytime"),

    (317, "noon in July!",
     "Cartoon calendar page showing 'JULY 15 - NOON' with a beach ball bouncing",
     "none",
     "bright sunny beach background with sand dunes and ocean waves",
     "summer calendar sheet reading 'JULY 15 - 12:00 PM' with a bouncing red and white striped beach ball and blazing comic sun overhead"),

    (318, "' It delays your hormones,",
     "Clock with hormone bottles stuck behind a locked traffic barricade",
     "none",
     "internal blood vessel diagram with comic street signs",
     "traffic jam of little medicine bottles labeled 'MELATONIN' and 'SLEEP HORMONES' stuck behind a bright orange construction roadblock"),

    (319, "trashes your deep sleep,",
     "Cartoon stick figure's dream cloud being tossed into a metal trash can",
     "none",
     "clean modern bedroom floor with metal wastebasket",
     "fluffy comic dream cloud labeled 'DEEP SLEEP (STAGE 4)' being crumpled up like waste paper and thrown into a metal garbage bin"),

    (320, "and scrambles millions of years",
     "DNA double helix twisted into an untidy scrambled spaghetti knot",
     "none",
     "clean genetics textbook background with molecular strands",
     "beautiful scientific DNA double helix suddenly twisting into a tangled comic bowl of yarn with question marks and error icons"),

    (321, "of evolutionary rhythm.",
     "Prehistoric evolutionary timeline from caveman to modern human glitching out",
     "none",
     "clean timeline graphic with digital static distortion waves",
     "classic silhouette parade of human evolution glitching with jagged static lines, representing broken evolutionary rhythm"),

    (322, "Researchers found",
     "Research scientist stick figure in lab coat pointing with stick at presentation board",
     "side",
     "university auditorium lecture stage with presentation screen",
     "scientist stick figure in side profile pointing with wooden dowel at research data graph, single scholarly black dot eye"),

    (323, "that taking people camping for",
     "Group of happy stick figures hiking with backpacks into pine wilderness",
     "side",
     "mountain pine forest trail with winding dirt path and snow-capped peaks",
     "three stick figures in side profile hiking with large backpacks and walking sticks, single cheerful black dot eye on each, heading toward woods"),

    (324, "just one single week",
     "Calendar block showing '7 DAYS' with pine tree and tent doodle",
     "none",
     "clean outdoor journal page with hand-drawn wooden texture",
     "seven consecutive calendar days highlighted with green checkmarks labeled '7 DAYS NO SCREENS', beside a cozy canvas tent sketch"),

    (325, "with zero screens resets their",
     "A pile of modern smartphones and tablets locked inside a wooden trunk in forest",
     "none",
     "outdoor camping ground with mossy pine log and pinecones",
     "vintage wooden steamer trunk padlocked shut, surrounded by crossed-out screen icons, completely detached from digital signals"),

    # --- ACT 7: THE MIDNIGHT SANCTUARY & THE ANCIENT WATCH (326 - 361) ---
    (326, "melatonin clock by two full hours,",
     "Clock with hands physically winding backwards by two hours with green sparkle",
     "none",
     "clean paper background with time-reverse curved arrows",
     "antique clock face with hands moving counterclockwise by exactly two hours, accompanied by magical golden sparkles and leaf doodles"),

    (327, "syncing them right back to sunset.",
     "Campers sitting around wilderness campfire as sunset perfectly matches melatonin rise",
     "front",
     "pine wilderness at sunset with orange sky fading into indigo and calm campfire",
     "two camper stick figures resting by campfire at dusk, both with two calm relaxed black dot eyes, body rhythm locking naturally with the sunset"),

    (328, "That's all it takes for three",
     "Simple stone archway framing the ancient starry night sky",
     "none",
     "prehistoric stone dolmen silhouette against vast cosmos",
     "clean ancient megalithic archway framing a brilliant starry night sky, linking modern simplicity to ancient eternity"),

    (329, "hundred thousand years of",
     "Golden ancient lineage banner rippling gently across the night sky",
     "none",
     "star-studded deep night sky with glowing cosmic ribbon",
     "glowing golden ribbon bearing the inscription '300,000 YEARS OF ANCESTRAL DNA' stretching across the frame over distant mountain silhouettes"),

    (330, "ancient biology to reassert itself.",
     "Stick figure's chest glowing with a serene ancient biological compass",
     "front",
     "peaceful natural wilderness clearing with starlit horizon",
     "stick figure standing with hand over heart, chest glowing with a golden ancestral compass rose, two calm grounded black dot eyes and peaceful smile"),

    (331, "We didn't just change our bedtime;",
     "Alarm clock being pushed forward from 9 PM to 1 AM on modern nightstand",
     "none",
     "modern nightstand surface with lamp and smartphone",
     "hand-drawn alarm clock face showing time pushed forcefully late into the night, beside an untouched book and glowing phone notifications"),

    (332, "we murdered an entire phase of",
     "Chalk outline of a sleeping person on a rug with a broken hourglass beside it",
     "none",
     "dark moody room with floorboards and dramatic noir shadows",
     "chalk outline of a resting figure on wooden floor with a broken hourglass whose sand has stopped flowing, symbolizing lost consciousness"),

    (333, "the human mind.",
     "Stylized silhouette of human head with a quiet glowing room in the center fading to dark",
     "none",
     "dark contemplative blueprint background with neural pathways",
     "profile contour of human head showing an intimate candlelit library inside the brain, with the candle wick being pinched out"),

    (334, "That peaceful,",
     "Stick figure resting in absolute serene stillness in moonlit bed with hands folded",
     "front",
     "dim peaceful bedroom with soft moonbeams illuminating the quilt",
     "stick figure lying peacefully in bed with hands folded gently over chest, two calm serene black dot eyes, expression full of deep quietude"),

    (335, "reflective midnight sanctuary",
     "Stick figure sitting by an open cottage window looking at calm silver moon",
     "front",
     "cozy window alcove with cushion, curtains, and view of tranquil night landscape",
     "stick figure sitting in window seat with knees pulled up, looking out into silver moonlit garden, two thoughtful gentle black dot eyes"),

    (336, "between first and second sleep is gone.",
     "A beautiful stone bridge spanning two cliffs cracking and crumbling into mist",
     "none",
     "dramatic misty chasm between two towering rock cliffs under starlight",
     "graceful arched stone bridge connecting 'First Sleep' cliff to 'Second Sleep' cliff collapsing into dust, leaving an empty chasm"),

    (337, "Instead,",
     "Harsh red neon sign buzzing with the word 'INSOMNIA' in a dark bedroom",
     "none",
     "dark modern bedroom wall with harsh buzzing red glow",
     "glowing red neon sign on modern apartment wall spelling 'INSOMNIA' with sharp electrical buzz lines casting angry shadows across room"),

    (338, "we have chronic insomnia,",
     "Stick figure tossing and turning frantically in tangled messy bedsheets",
     "front",
     "messy modern bedroom at night with rumpled blankets and pillows everywhere",
     "stick figure tangled in twisted sheets, tossing from side to side, two wide exhausted stressed black dot eyes, spiral frustration lines"),

    (339, "and we pop sleeping pills",
     "Stick figure sitting on bed edge popping a blue capsule with glass of water",
     "side",
     "modern nightstand cluttered with prescription pill bottles and water glass",
     "stick figure in side profile swallowing a sleep pill from a plastic prescription bottle, single defeated weary black dot eye and slumped shoulders"),

    (340, "because we think our bodies are broken.",
     "Stick figure looking in bathroom mirror with sad face and 'BROKEN?' thought bubble",
     "front",
     "harshly lit modern bathroom with fluorescent mirror lights",
     "stick figure leaning on bathroom sink looking at reflection, two sad drooping black dot eyes, frowning mouth, with comic broken wrench icon above"),

    (341, "But what if waking up",
     "Stick figure's eyes opening calmly in bed at 3:00 AM with zero panic",
     "front",
     "dark peaceful bedroom with soft ambient blue night light",
     "stick figure opening eyes in bed, two clear tranquil black dot eyes looking around with peaceful curiosity rather than anxiety, smooth brow"),

    (342, "at three in the morning",
     "Digital clock glowing '03:00 AM' with soft peaceful blue digits",
     "none",
     "clean nightstand surface in tranquil ambient darkness",
     "bedside digital clock displaying '03:00 AM', bathed in calm, gentle blue tones, surrounded by soft quiet shadows"),

    (343, "and staring at the ceiling isn't",
     "Stick figure lying on back looking up at bedroom ceiling with gentle peaceful gaze",
     "front",
     "calm bedroom with ceiling showing soft dappled starlight reflections",
     "stick figure lying flat under duvet with arms relaxed, two wide thoughtful black dot eyes staring softly at the ceiling in serene contemplation"),

    (344, "a medical failure at all?",
     "A medical diagnosis checklist with red failure stamps being wiped away cleanly",
     "none",
     "clean paper clipboard with eraser marks",
     "medical chart labeled 'Sleep Pathology' having red 'DEFECTIVE' stamps erased by a gentle brush, revealing healthy natural parchment beneath"),

    (345, "What if that midnight stillness",
     "Stick figure sitting on edge of bed taking a deep breath of quiet night air",
     "front",
     "peaceful dark bedroom with open window letting in cool night breeze",
     "stick figure sitting peacefully on bed edge, hands on knees, two gentle closed dash eyes, breathing in the still quiet air with faint smile"),

    (346, "is just your ancient caveman",
     "Faint glowing outline of ancient hunter ancestor standing protectively beside bed",
     "side",
     "modern bedroom blending softly into ethereal prehistoric savannah at dusk",
     "translucent glowing silhouette of an ancient hunter stick figure in fur pelt standing beside modern bed, single wise protective black dot eye"),

    (347, "brain waking up for 'the watch,'",
     "Comic brain wearing a prehistoric fur pelt holding a tiny ancient torch",
     "front",
     "warm campfire clearing inside the mind with soft embers",
     "cute cartoon brain character wearing a little animal fur headband, holding up a tiny torch, two alert friendly black dot eyes, on watch"),

    (348, "looking around for the campfire,",
     "Prehistoric stick figure peering curiously through darkness searching for embers",
     "side",
     "dark nocturnal wilderness with faint starlight on rocks",
     "ancient stick figure in side profile cupping hand above brow peering into the dark distance, single searching black dot eye, looking for fire"),

    (349, "and wondering why",
     "Stick figure looking down with bewildered humorous face at glowing laptop screen",
     "front",
     "dark bedroom desk with blinding glare from open corporate laptop",
     "stick figure sitting at desk staring at screen, two baffled wide black dot eyes, hands thrown up in comic disbelief at late-night emails"),

    (350, "on earth you're stressing over",
     "Flock of aggressive cartoon red email envelopes swooping around stick figure's head",
     "front",
     "modern bedroom desk with chaotic swirling notification badges",
     "stick figure ducking as fluttering cartoon red email envelopes with angry eyebrows swarm around, two overwhelmed frantic black dot eyes"),

    (351, "emails instead of enjoying the silence?",
     "Stick figure closing the laptop firmly and turning to gaze out quiet starry window",
     "side",
     "peaceful dark bedroom with open window showing starry night",
     "stick figure in side profile snapping laptop closed with decisive 'CLACK', single peaceful black dot eye looking toward the quiet starlit window"),

    (352, "For hundreds of thousands of years,",
     "Vast sweeping nocturnal panoramic view of ancient Earth under unpolluted starry cosmos",
     "none",
     "untouched Paleolithic Earth landscape under glorious crystalline Milky Way",
     "breathtaking wide landscape of untouched ancient Earth: winding silver river, dark rolling savannah hills, and the immense glowing Milky Way"),

    (353, "your ancestors gathered around",
     "Tribe of stick figures gathered peacefully around a warm glowing hearth",
     "front",
     "prehistoric campsite under deep velvet night sky with twinkling stars",
     "five stick figures seated together in circle around glowing embers, all with round white heads and two warm affectionate black dot eyes"),

    (354, "crackling embers,",
     "Close-up of radiant wood embers with delicate golden sparks drifting toward sky",
     "none",
     "dark hearth floor with smooth river stones and glowing red embers",
     "macro view of crackling campfire coals glowing deep crimson and gold, tiny sparks ascending like miniature stars into the upper frame"),

    (355, "shared hilarious stories,",
     "Ancient stick figure telling a funny story by fire while friends laugh warmly",
     "front",
     "warm circular campfire glow with dancing shadows",
     "standing stick figure gesturing with open arms telling a joke, surrounded by laughing friends with happy curved eyes, deep human connection"),

    (356, "and rested in peaceful rhythms",
     "Stick figures sleeping together peacefully in cave nest under warm animal pelts",
     "front",
     "safe cave shelter illuminated by the soft dying embers of the hearth",
     "group of stick figures sleeping side by side in deep peaceful harmony, all with two gentle sleeping dash eyes, expressions of complete security"),

    (357, "beneath a sparkling Milky Way.",
     "Magnificent hand-drawn Milky Way galaxy arching across the entire 16:9 widescreen frame",
     "none",
     "vast deep indigo night sky filling entire frame from edge to edge",
     "stunning full-bleed illustration of the Milky Way: swirling river of countless hand-drawn ink stars, cosmic dust clouds, and constellation lines"),

    (358, "We traded that entire cosmic",
     "Two hands holding: one hand holds a sparkling galaxy jar, one hand holds an electric plug",
     "none",
     "clean split parchment background with cosmic stardust on left, electrical wires on right",
     "left hand holds a magical glass jar glowing with swirling galaxies and stars; right hand holds a cold grey plastic electrical power plug"),

    (359, "connection for an electric light switch -",
     "Close-up of modern plastic rocker light switch casting cold harsh white glare",
     "none",
     "plain sterile drywall background with harsh angular spotlight glare",
     "clean modern plastic toggle switch flipped down into the 'ON' position, casting flat sterile white illumination with zero stars"),

    (360, "and we didn't even realize what we lost.",
     "Stick figure standing alone by modern light switch gazing wistfully at starlit window",
     "side",
     "modern apartment room with light switch on wall and open window showing faint distant stars",
     "modern stick figure in side profile with finger still resting on the light switch, turning head back toward the night window, single thoughtful black dot eye and wistful smile"),

    (361, "Closing contemplative frame: fading campfire embers merging into distant galaxy stars.",
     "Campfire smoke rising gracefully and seamlessly dissolving into the stars of the Milky Way",
     "none",
     "full bleed nocturnal cosmic wilderness background with deep indigo paper texture",
     "delicate white smoke wisp from a dying prehistoric campfire rising gracefully into the night sky, its glowing sparks seamlessly transforming into the twinkling stars of the Milky Way galaxy, widescreen 16:9 full bleed, peaceful poetic finale"),
]
