"""
Storyboard Visual Data: Part 1 (Shots 001 - 120)
Project: 2- What Did Ancient Humans Do at Night
"""

SHOTS_PART_1 = [
    # --- ACT 1: THE MODERN LIGHT SWITCH & SENSORY DEPRIVATION (1 - 44) ---
    (1, "Later tonight,", 
     "Modern stick figure walking down a cozy hallway toward bedroom at dusk",
     "front",
     "cozy modern apartment hallway with beige walls, wooden floorboards, and framed artwork",
     "modern stick figure walking casually toward a doorway with two simple expressive black dot eyes and a calm neutral mouth"),

    (2, "you're going to walk into a room,",
     "Stick figure entering bedroom and reaching toward the wall",
     "side",
     "dimly lit modern bedroom with bed, nightstand, and window showing evening twilight",
     "stick figure in side profile stepping into the dark room, arm outstretched toward the doorframe, single simple expressive black dot eye and neutral line mouth"),

    (3, "flick a tiny piece of plastic on the wall,",
     "Close-up of a modern rocker light switch on beige wall",
     "none",
     "clean modern beige painted drywall background with subtle plaster texture",
     "macro illustration of a rectangular white plastic light switch being flipped upward, tiny comic 'CLICK' sound-effect doodle"),

    (4, "and boom -",
     "Dynamic comic starburst burst of white and golden light rays",
     "none",
     "dramatic dark-to-light gradient background with comic speedlines radiating from center",
     "dynamic comic explosion burst of golden-yellow and pure white light rays erupting across the frame"),

    (5, "instant artificial sun.",
     "Brightly illuminated modern bedroom with ceiling fixture emitting light rays",
     "none",
     "modern bedroom interior with wooden nightstand, cozy bed with fluffy pillows, and tidy desk",
     "central ceiling light fixture glowing intensely like a miniature sun with stylized comic rays filling the entire room"),

    (6, "You won't think about it.",
     "Modern stick figure casually tossing keys onto a table without caring",
     "front",
     "bright modern bedroom with wooden desk, chair, and floor rug",
     "stick figure tossing car keys onto the desk, expression totally nonchalant, two simple expressive black dot eyes and flat line mouth"),

    (7, "You might even complain",
     "Stick figure standing with hands on hips looking annoyed at the ceiling light",
     "front",
     "modern minimalist apartment interior with warm lighting and wooden floorboards",
     "stick figure with hands on hips, head tilted upward with an annoyed expression, two squinting black dot eyes and a wavy unimpressed mouth"),

    (8, "that the bulb is slightly too",
     "Close-up of glowing incandescent light bulb with comic warmth gauge",
     "none",
     "clean muted grey wall background with faint shadows",
     "close-up of an illuminated light bulb with squiggly heat lines, beside a small cartoon warmth scale showing amber versus white tones"),

    (9, "warm for your aesthetic.",
     "Modern stick figure hipster inspecting minimalist room with coffee mug",
     "side",
     "stylish modern room with potted succulent plant, abstract wall frame, and sleek shelf",
     "stick figure in side profile holding a steaming white mug, looking critically at the ceiling light with a single judgmental black dot eye and smirking mouth"),

    (10, "But for 99.9% of human history,",
     "Infographic timeline bar showing vast dark prehistory vs tiny modern light sliver",
     "none",
     "clean paper parchment background with horizontal measurement marks",
     "long dark charcoal timeline bar spanning 99.9% of the frame labeled 'Ancient Darkness', terminating in a hairline yellow fraction labeled 'Electric Light'"),

    (11, "that switch didn't exist.",
     "Cave stone wall with a comical dashed outline where a light switch should be",
     "none",
     "rough textured limestone prehistoric cave wall with natural crevices and cracks",
     "a humorous dashed chalk outline of a modern light switch on the bare rock with a bold hand-drawn question mark"),

    (12, "When the sun went down,",
     "Vast Paleolithic landscape with fiery sun setting behind jagged mountain peaks",
     "none",
     "panoramic prehistoric savannah at sunset with jagged mountain ridge and tall swaying grass",
     "dramatic glowing orange and crimson sun sinking beneath the horizon, casting deep purple and black shadows across the wild landscape"),

    (13, "the entire planet turned",
     "Stylized vector Earth globe in space plunging into complete darkness",
     "none",
     "deep dark space background dotted with distant hand-drawn star clusters",
     "stylized circular Earth rotating into nighttime darkness, continents completely devoid of artificial city light grids"),

    (14, "into a sensory deprivation chamber.",
     "Stick figure floating in total pitch-black void looking completely lost",
     "front",
     "pitch-black void background with subtle deep charcoal stippled paper texture",
     "isolated stick figure floating in the center of the dark abyss with wide bewildered black dot eyes and an open bewildered mouth"),

    (15, "You couldn't see your own hand",
     "Stick figure holding hand inches from face in pitch darkness straining to see",
     "front",
     "dark shadowy room interior with heavy charcoal shading and faint ambient moonlight",
     "stick figure holding open hand right in front of face, leaning forward with two wide strained black dot eyes and a nervous squiggly mouth"),

    (16, "in front of your face,",
     "Close-up of stick figure's face in deep shadow with hand barely outlined",
     "front",
     "deep charcoal black vignette background with subtle ink crosshatching",
     "close-up of white circular head with two wide curious black dot eyes staring intently into darkness, faint black contour of fingers barely visible"),

    (17, "let alone whatever sharp object",
     "Low-angle shot of ground with jagged flint stone and thorny brambles",
     "none",
     "dark sandy ground with rough pebbles, thorny dry shrubs, and sharp prehistoric limestone rocks",
     "detailed low-angle view of a pointed flint rock jutting upward dangerously from the dark soil with spiky comic outline"),

    (18, "was waiting to destroy your toe.",
     "Comedic impact: stick figure stubbing toe on rock with dramatic pain stars",
     "front",
     "dark outdoor prehistoric terrain at night with rocky ground and faint starlight",
     "stick figure hopping on one foot clutching injured toe, comic yellow impact starburst on foot, two wide agonized dot eyes and open shouting mouth"),

    (19, "Today,",
     "Bright modern living room interior with cozy furniture and warm floor lamp",
     "none",
     "warm contemporary living room with clean hardwood floors, grey armchair, and bookshelf",
     "peaceful illuminated living space with soft warm lighting from an elegant standing floor lamp, casting gentle shadows"),

    (20, "true darkness is something you",
     "Modern stick figure holding glowing smartphone looking curious",
     "front",
     "cozy modern bedroom interior with soft ambient night shadows and bookshelf",
     "modern stick figure standing beside bed holding a glowing phone, two simple expressive black dot eyes looking thoughtful with a gentle curved smile"),

    (21, "only experience during a power",
     "Suburban street during a blackout with houses plunged into pitch black",
     "none",
     "suburban street neighborhood background at night under clear starlit sky",
     "row of dark houses with black unlit windows, dead streetlights along the sidewalk, and stars twinkling brightly overhead"),

    (22, "outage or inside an expensive",
     "Stick figure standing baffled in dark kitchen holding useless toaster",
     "front",
     "dark modern kitchen illuminated only by faint window moonlight with counters and cupboards",
     "stick figure standing in dark holding a shiny two-slice toaster with plug dangling, scratching head with two confused black dot eyes and wavy mouth"),

    (23, "escape room.",
     "Stick figure inside locked mystery escape room holding UV flashlight",
     "side",
     "creepy escape room interior with stone brick wallpaper, locked heavy chest, and wall clock",
     "stick figure in side profile examining a padlock on the wall with a tiny UV flashlight, single focused black dot eye and determined mouth"),

    (24, "But for over three hundred",
     "Bold hand-drawn typography '300,000 YEARS' carved into prehistoric monolith",
     "none",
     "starlit prehistoric night sky background with rugged dark earth below",
     "ancient stone megalith carved with bold comic ink letters '300,000 YEARS', subtle crosshatching and dramatic moonlight edge glow"),

    (25, "thousand years,",
     "Long procession of prehistoric ancestors walking into the vast distance",
     "side",
     "wide prehistoric valley at dusk with rolling hills and winding river under darkening sky",
     "silhouette line of stick-figure hunter-gatherers in side profile marching in single file across the landscape, each with a single dot eye visible"),

    (26, "every single one of your ancestors",
     "Three prehistoric stick figures in animal pelts standing together proudly",
     "front",
     "prehistoric campsite background with limestone boulder and dry golden grass",
     "three ancient stick figures in simple brown fur tunics, each with a round white head, two simple expressive black dot eyes, and friendly confident smiles"),

    (27, "spent roughly half of their entire",
     "Infographic pie chart divided exactly 50/50 between golden sun and dark stars",
     "none",
     "clean textured paper background with clean graphic borders",
     "large circular comic infographic pie chart: left half bright yellow with smiling sun, right half deep navy black with crescent moon and stars"),

    (28, "earthly existence in pitch-black nothingness.",
     "Lonely prehistoric stick figure sitting on high boulder under vast dark night",
     "front",
     "panoramic nocturnal Paleolithic wilderness with distant mountain silhouettes and dark sky",
     "small stick figure sitting on a cliff edge looking up at the endless dark sky, two small contemplative black dot eyes and peaceful neutral mouth"),

    (29, "No flashlights.",
     "Bold crossed-out red circle over a modern yellow plastic flashlight doodle",
     "none",
     "plain textured paper background with subtle grey stippling",
     "hand-drawn yellow tactical flashlight doodle with a bright red 'NO' prohibition circle and diagonal slash across it"),

    (30, "No scented candles.",
     "Bold crossed-out red circle over a luxury scented candle jar with aroma wisps",
     "none",
     "plain textured paper background with subtle grey stippling",
     "glass jar candle doodle with stylized lavender aroma smoke swirls, covered by a bold red prohibition circle and slash"),

    (31, "Just a giant void,",
     "Vast expansive dark sky dominating the frame over dark earth silhouette",
     "none",
     "deep inky charcoal wash sky filling ninety percent of the 16:9 widescreen frame",
     "panoramic view of the immense black night sky with gentle textured ink gradients and low rolling hill silhouettes at the bottom"),

    (32, "a bunch of distant stars,",
     "Hand-drawn constellation patterns and twinkling stars across the night sky",
     "none",
     "deep dark midnight blue paper background with soft cosmic grain",
     "detailed ink doodles of crisp four-pointed stars, constellation connection lines, and drifting stardust across the upper frame"),

    (33, "and whatever sad little embers",
     "Close-up of dying campfire with grey ash and three tiny glowing orange sparks",
     "none",
     "dark sandy soil ground background with charred wood pieces",
     "close-up of a small mound of grey wood ash with three tiny glowing orange embers and delicate curling wisps of white smoke"),

    (34, "they managed to keep from",
     "Prehistoric stick figure kneeling down cupping hands around dying embers",
     "side",
     "prehistoric campsite ground with river stones and dark nighttime shadows",
     "prehistoric stick figure on knees in side profile, cupping hands gently around faint embers, single attentive black dot eye and focused mouth"),

    (35, "blowing away.",
     "Stick figure blowing gently onto embers as delicate orange sparks lift into air",
     "side",
     "dark campsite setting with soft ambient night illumination from sparks",
     "stick figure in side profile blowing air through pursed lips, single expressive black dot eye, tiny comic wind lines and floating orange sparks"),

    (36, "So what on earth were they doing",
     "Prehistoric stick figure scratching head with big question mark overhead",
     "front",
     "nocturnal wilderness background with starry sky and silhouette of acacia tree",
     "stick figure standing with one hand scratching chin, head tilted quizzically, two wide black dot eyes, and a bold curly question mark floating above"),

    (37, "for all those hours?",
     "Hand-drawn stone clock dial shrouded in darkness with ticking question marks",
     "none",
     "textured parchment background with charcoal shading",
     "ancient circular stone clock face doodle with cracked Roman numerals, surrounded by floating ink question marks and swirling night mist"),

    (38, "As it turns out,",
     "Hand-drawn magnifying glass revealing hidden cave painting doodles",
     "none",
     "dark cave stone wall texture with rough fissures",
     "a large comic magnifying glass focused on ancient red ochre stick-figure cave drawings, revealing animated details underneath"),

    (39, "the answer completely redefines",
     "Ancient stone tablet cracking open with bright golden light beaming from within",
     "none",
     "subtle textured paper background with dramatic central lighting",
     "heavy carved stone slab splitting down the center with radiant comic golden sunbeams bursting outward, signifying revelation"),

    (40, "human sleep,",
     "Prehistoric stick figure sleeping peacefully curled in soft animal furs",
     "front",
     "dim cave interior with warm stone floor and cozy nest of reindeer pelts",
     "stick figure lying curled on side sleeping peacefully, two simple sleeping dash-line eyes, gentle content smile, and small 'Zzz' doodles"),

    (41, "storytelling,",
     "Stick figure standing by campfire acting out hunting story with wide gestures",
     "front",
     "open prehistoric savannah campsite around crackling orange fire",
     "stick figure standing animatedly beside the fire with arms raised like animal horns, two wide expressive black dot eyes, and open enthusiastic mouth"),

    (42, "and why you're awake",
     "Modern stick figure lying wide awake in bed staring up at dark bedroom ceiling",
     "front",
     "modern dark bedroom at night with bed frame, nightstand, and blue moonlight on blankets",
     "stick figure lying flat on back with duvet pulled to chest, two wide unblinking black dot eyes staring blankly at the ceiling in complete alertness"),

    (43, "at three in the morning right now.",
     "Extreme close-up of glowing green digital alarm clock reading '03:00 AM'",
     "none",
     "dark wooden bedside nightstand surface with faint reflection",
     "macro illustration of an electronic alarm clock face with bright glowing green LED segments clearly displaying '03:00 AM'"),

    (44, "To understand any of this,",
     "Parchment page with comic flowchart linking question mark to campfire icon",
     "none",
     "vintage paper texture background with hand-drawn ink border accents",
     "clean comic mind-map diagram with hand-drawn arrows connecting modern insomnia to ancient prehistoric fire hearths"),

    # --- ACT 2: THE FIRE REVOLUTION & THE DANGER ZONE (45 - 94) ---
    (45, "we have to talk about fire.",
     "Central roaring campfire with bold crackling comic flames and flying sparks",
     "none",
     "dark Paleolithic campsite with circle of smooth river stones on sandy ground",
     "vibrant roaring campfire with stylized black ink contour lines, bright orange and golden yellow core flames, and sparks rising into the night"),

    (46, "The earliest rock-solid evidence",
     "Archaeological excavation scene with fossilized charcoal layers in stone",
     "none",
     "geological rock cross-section with stratified sediment bands and measurement ruler doodle",
     "detailed cross-section of ancient cave floor showing dark burnt charcoal strata preserved beneath million-year-old rock sediment"),

    (47, "of hominids taming fire comes",
     "Early hominid stick figure proudly holding a burning wooden torch",
     "side",
     "rocky prehistoric hillside at dusk with rugged terrain and mountain background",
     "early hominid stick figure in side profile holding aloft a blazing pine torch, single wide awe-struck black dot eye, and happy grinning mouth"),

    (48, "from Wonderwerk Cave",
     "Wide panoramic view of the enormous entrance of Wonderwerk Cave in South Africa",
     "none",
     "rugged South African Kalahari landscape with red earth, acacia trees, and vast limestone dolomite hillside",
     "majestic gaping stone archway entrance of Wonderwerk Cave leading into deep ancient darkness, warm sunlight illuminating the rock entrance"),

    (49, "in South Africa,",
     "Stylized outline map of the African continent highlighting South Africa",
     "none",
     "textured cream parchment map background with compass rose doodle",
     "clean hand-drawn map of Africa with bold ink outline, a glowing red location pin and radiating circle marking South Africa"),

    (50, "about one million years ago.",
     "Bold stone inscription with comic chisel doodle reading '1,000,000 BC'",
     "none",
     "rough stone tablet background with prehistoric chiseling marks",
     "heavy stone rock slab with deep chiseled numbers '1,000,000 BC', a small stone mallet and flint chisel resting beside it"),

    (51, "But fire wasn't just ancient",
     "Stick figure warming hands near a stone hearth looking comfortable",
     "front",
     "cozy prehistoric rock shelter with warm glowing firelight on limestone walls",
     "ancient stick figure kneeling near glowing coals with open hands outstretched, two happy black dot eyes and peaceful smiling mouth"),

    (52, "central heating.",
     "Humorous comparison: modern metal radiator doodle vs prehistoric campfire doodle",
     "none",
     "clean split-screen paper background with vertical divider line",
     "left side shows a modern white cast-iron radiator with steam lines; right side shows a crackling stone-age fire pit with red heat waves"),

    (53, "It completely broke",
     "A stylized stone sundial splitting in half with dramatic comic impact lines",
     "none",
     "textured background with cracked prehistoric earth",
     "ancient carved stone circular sundial cracking down the center into two separate jagged pieces with comic vibration lines"),

    (54, "and rebuilt the human schedule.",
     "New hand-drawn 24-hour circular clock divided into day, evening fire, and sleep",
     "none",
     "clean vintage notebook background with ink grid guidelines",
     "circular clock diagram divided into three colorful sections: golden daytime foraging, warm orange evening fire gathering, and deep blue night rest"),

    (55, "Before fire,",
     "Dark prehistoric jungle wilderness at dusk under ominous brooding clouds",
     "none",
     "dense primeval forest with tall gnarly tree trunks, hanging vines, and murky shadows",
     "atmospheric prehistoric forest landscape at sundown, shadows deepening ominously between twisted tree roots"),

    (56, "our ancestors were basically",
     "Small primitive stick figure standing timidly in tall wild grass looking vulnerable",
     "front",
     "vast open African savannah grassland at twilight with distant predator silhouettes",
     "timid ancient stick figure standing alone in tall grass, shoulders hunched, two wide nervous black dot eyes and trembling squiggly mouth"),

    (57, "helpless primates",
     "Group of early hominid stick figures huddled together looking small and defenseless",
     "front",
     "rocky prehistoric savannah outcrop at sundown",
     "three small early hominid stick figures clutching each other tightly, all with round white heads, two wide worried black dot eyes, and shivering outlines"),

    (58, "with zero night vision.",
     "Stick figure with comical oversized eyeballs looking into a solid black wall",
     "front",
     "pitch-black cavern background with comic spotlight on stick figure",
     "stick figure with wide circular white eyes strained open, two large black dot pupils staring forward into blackness with zero visibility"),

    (59, "Once dusk hit,",
     "Sun dipping below tree line as long dark predator shadows stretch across ground",
     "none",
     "savannah forest border with red-orange sunset sky fading into deep violet",
     "sun vanishing behind silhouette of acacia canopy, stretching gigantic dark predator shadows across the golden ground"),

    (60, "you scrambled up a tree,",
     "Stick figure frantically shinnying up a tall knotted tree trunk with flailing limbs",
     "side",
     "prehistoric savannah tree with thick gnarly branches against evening sky",
     "stick figure in side profile scrambling furiously up a rough tree trunk, arms and legs wrapped tight, single terrified black dot eye looking down"),

    (61, "curled into an anxious little ball,",
     "Stick figure curled into tight fetal ball on high tree branch shivering",
     "front",
     "high canopy branch overlooking dark wilderness under starlight",
     "stick figure curled into a tight ball on a horizontal branch, knees to chest, shivering motion lines, two tightly squeezed black dot eyes"),

    (62, "and prayed you didn't sneeze.",
     "Stick figure in tree tightly pinching nose with fingers with bulging eyes",
     "front",
     "tree foliage at night with dark leaves and glowing star background",
     "stick figure in tree branch clamping fingers tightly over nose, cheeks puffed out, two wide bulging black dot eyes terrified of making a sound"),

    (63, "Wandering around",
     "Stick figure tiptoeing blindly into darkness with hands outstretched",
     "side",
     "pitch black wilderness with rugged rocky terrain and lurking shadows",
     "stick figure in side profile tiptoeing gingerly into deep darkness with arms extended forward, single nervous black dot eye and biting lip"),

    (64, "in the dark was essentially",
     "Stick figure walking unknowingly toward a pair of glowing yellow predator eyes",
     "side",
     "nocturnal savannah with dark bushes and ominous black silhouettes",
     "stick figure in side profile walking forward while a pair of sinister glowing yellow cat eyes watches from the bushes behind him, single dot eye oblivious"),

    (65, "volunteering to be a midnight snack.",
     "Comedic predator menu board with 'Stick Figure Stew' written in bone letters",
     "none",
     "dark savannah brush background with subtle moonlight",
     "humorous wooden chalkboard menu hanging from a branch titled 'Tonight's Menu: Fresh Primate Snack', complete with fork and knife doodle"),

    (66, "Compared to leopards,",
     "Sleek cartoon leopard crouched on rock with glowing sharp night-vision eyes",
     "side",
     "dark rocky African savannah cliff under night sky",
     "stylized ink leopard in side profile crouched low on rock ledge with sharp claws and glowing green reflective eyes peering into the dark"),

    (67, "hyenas,",
     "Cackling cartoon hyena with toothy grin and bright reflective yellow eyes",
     "front",
     "shadowy African bush at night with dry thorny thicket",
     "humorous stylized hyena with spotted coat, jagged toothy grin, and two glowing yellow eyes staring forward with sinister humor"),

    (68, "and wolves -",
     "Proud cartoon dire wolf standing atop boulder howling at the crescent moon",
     "side",
     "rocky ridge under starry sky with crisp crescent moon",
     "muscular stylized wolf silhouette in side profile standing atop a rock crag, head tilted upward howling, single sharp glowing eye"),

    (69, "who basically had built-in",
     "Comic graphic of a leopard wearing high-tech night-vision goggles",
     "front",
     "dark forest clearing with green ambient radar glow",
     "humorous cartoon leopard sitting upright wearing futuristic twin-lens green night-vision goggles with green scanning beams projecting outward"),

    (70, "night-vision goggles -",
     "First-person green night-vision reticle view showing a stick figure glowing bright",
     "none",
     "green phosphor night-vision HUD overlay with digital battery icons and crosshairs",
     "predator's POV through green night-vision lens showing a stick figure highlighted in bright thermal white in the dark distance"),

    (71, "human eyes in the dark are",
     "Human eye diagram looking fuzzy and blurred in pitch blackness",
     "none",
     "dark anatomical textbook paper background",
     "comic cross-section diagram of human eye showing confused question marks bouncing off the retina with zero night-vision receptors"),

    (72, "completely useless.",
     "Stick figure walking face-first into a large tree trunk with comic stars",
     "side",
     "dark primeval forest with thick twisted tree trunks",
     "stick figure in side profile crashing head-first into a wooden tree trunk, spiral dizziness lines, comic yellow impact stars, single dizzy spiral eye"),

    (73, "Fire changed the entire food chain.",
     "Dynamic food web diagram showing humans jumping from bottom to top above predators",
     "none",
     "clean educational paper background with arrows and tier brackets",
     "infographic pyramid food chain where a stick figure holding a torch leaps from the prey tier right above snarling big cats to the very top"),

    (74, "A campfire creates a thirty-foot",
     "Top-down bird's-eye view of a bright campfire radiating a 30-foot circular dome",
     "none",
     "dark nocturnal terrain viewed from directly above",
     "top-down schematic view showing central orange campfire emitting a glowing 30-foot circular perimeter ring of golden safety light"),

    (75, "glowing dome of 'do not eat me.'",
     "Campfire glowing dome with a humorous protective energetic forcefield doodle",
     "front",
     "prehistoric night camp surrounded by pitch black wilderness",
     "bright campfire casting a radiant bubble-like dome of golden light, with stick figures resting safely inside while shadows bounce off"),

    (76, "Inside that circle,",
     "Three stick figures sitting warmly around the campfire laughing and roasting meat",
     "front",
     "illuminated circle of smooth river stones, animal furs, and crackling fire",
     "three prehistoric stick figures sitting peacefully by fire, each with round white head, two happy black dot eyes, smiling mouths, holding wooden roasting skewers"),

    (77, "predators stayed away.",
     "Silhouettes of shadowy predators pacing frustratedly outside the light ring",
     "none",
     "dark perimeter just beyond the campfire light edge",
     "black silhouettes of snarling leopards and hyenas pacing back and forth outside the boundary of light, eyes glowing with frustrated squints"),

    (78, "Outside that circle,",
     "Dramatic contrast line: bright warm safety on left, ominous dark void on right",
     "none",
     "split composition: warm golden glow on left, pitch black ominous abyss on right",
     "sharp visual border dividing the glowing golden campfire zone from the frightening pitch-black darkness filled with glowing predator eyes"),

    (79, "you were on the menu.",
     "Stick figure tip-toeing outside the line with a giant cartoon fork pointed at him",
     "side",
     "dark wilderness edge with looming giant predator shadows",
     "stick figure in side profile foolishly stepping beyond the light line, a giant cartoon fork and knife hovering humorously above, single startled dot eye"),

    (80, "This isn't hyperbole -",
     "A modern anthropological field notebook with stamped 'CONFIRMED' seal",
     "none",
     "weathered field notebook page with handwritten observational field notes",
     "open field journal with sketched campfire radius diagram, scientific data table, and a bold red rubber stamp reading 'CONFIRMED FACT'"),

    (81, "even today,",
     "Modern calendar doodle showing year 2026 flipping beside a savannah silhouette",
     "none",
     "clean paper background with warm morning horizon gradient",
     "modern flip calendar doodle showing current date beside a hand-drawn savannah acacia tree, linking ancient past to modern present"),

    (82, "field studies show",
     "Modern anthropologist stick figure with binoculars and field hat taking notes",
     "side",
     "African savannah camp at dusk with canvas tent and research vehicle in background",
     "anthropologist stick figure in side profile wearing explorer hat, holding binoculars and clipboard, single sharp observant black dot eye"),

    (83, "that people in modern",
     "Modern hunter-gatherer village at night with traditional thatch huts and central fire",
     "none",
     "open Kalahari desert clearing under starry sky with thatch grass dwellings",
     "village clearing with traditional round dome huts arranged in circle around a communal fire pit casting warm flickering light"),

    (84, "hunter-gatherer tribes",
     "Group of modern tribal stick figures gathered safely around glowing hearth",
     "front",
     "warm desert sand ground illuminated by communal campfire",
     "four stick figures gathered around hearth, each with round white head, two expressive black dot eyes, engaged in peaceful communal conversation"),

    (85, "who wander away from the fire",
     "Single stick figure foolishly walking away from the fire into tall dark grass",
     "back",
     "dark desert brush at night with diminishing campfire glow behind",
     "stick figure seen from behind (back pose) walking away from the warm fire into the dark abyss, round white head with zero facial features visible"),

    (86, "at night have a nasty habit of",
     "Pair of red predatory eyes opening in the dark brush right in front of the walker",
     "none",
     "deep dark tangled savannah brush in total shadow",
     "pitch black bushes where two menacing crimson eyes slowly open, accompanied by comic jagged teeth and a sinister low growl sound-wave"),

    (87, "getting eaten.",
     "Comedic comic poof cloud with stick figure shoes left on the ground",
     "none",
     "dark savannah clearing with faint moonlight",
     "comic dust poof cloud labeled 'CHOMP!', with a small pair of prehistoric leather sandals left standing on the empty dirt"),

    (88, "But here's the really wild part:",
     "Stick figure pointing excitedly at an illuminated lightbulb idea overhead",
     "front",
     "clean warm study background with books and charts",
     "stick figure pointing one index finger up in revelation, two wide energetic black dot eyes, open grinning mouth, and a glowing lightbulb idea doodle"),

    (89, "fire didn't just save humans",
     "Stick figure holding a torch shielding another stick figure from a cartoon lion",
     "side",
     "nocturnal savannah with campfire glow on rocks",
     "brave stick figure in side profile brandishing blazing torch toward a retreating stylized lion, single brave black dot eye and determined scowl"),

    (90, "from becoming leopard food.",
     "Cartoon leopard sulking away with head hanging low and tail between legs",
     "side",
     "dark perimeter rocks fading into night shadows",
     "comical leopard in side profile slinking away into darkness with droopy whiskers, disappointed frown, and tail tucked between legs"),

    (91, "It gifted them free time.",
     "Ancient stick figure receiving an oversized wrapped gift box containing a clock",
     "front",
     "warm campfire clearing with gentle flickering illumination",
     "stick figure happily unwrapping an oversized gift box, out of which floats a glowing golden clock, two thrilled black dot eyes and beaming smile"),

    (92, "Before hearths,",
     "Primitive stick figure working under bright sun looking exhausted",
     "front",
     "open prehistoric landscape under harsh blinding midday sun",
     "prehistoric stick figure sweating under beating sun with stone axe in hand, two weary drooping black dot eyes and tongue sticking out"),

    (93, "the workday ended at sunset.",
     "Sun dropping below horizon while stick figure drops heavy wooden spear",
     "side",
     "savannah grassland at sunset with orange horizon",
     "stick figure in side profile dropping heavy spear to the ground as the sun touches the horizon, single tired black dot eye and sigh doodle"),

    (94, "That was maybe twelve hours in summer,",
     "Visual infographic bar showing long 12-hour golden summer day",
     "none",
     "clean paper background with summer sun icon",
     "horizontal yellow progress bar showing '12 HOURS SUMMER LIGHT' with a blazing sun icon, followed by an equally long dark bar"),

    (95, "and barely eight in winter.",
     "Visual infographic bar showing short 8-hour winter day with shivering snowflakes",
     "none",
     "clean paper background with winter snowflake icon",
     "short blue progress bar showing '8 HOURS WINTER LIGHT' beside falling snowflake doodles, followed by an enormous 16-hour black bar"),

    (96, "Fire suddenly dumped two to four",
     "Campfire dramatically pouring glowing hour symbols from a cornucopia",
     "none",
     "warm campfire setting with energetic golden lighting",
     "magical comic campfire spilling dozens of glowing hour glass and 'HOUR' text bubbles directly onto the campsite floor"),

    (97, "bonus hours onto every single day.",
     "Stick figure juggling three glowing '+1 HOUR' golden coins around the fire",
     "front",
     "nocturnal campsite under starlit sky with crackling campfire",
     "cheerful stick figure juggling three glowing golden disks labeled '+1 HOUR', two happy black dot eyes, and a broad laughing smile"),

    (98, "And over thousands of",
     "Stylized calendar pages rapidly flying off into the night sky like glowing birds",
     "none",
     "starry sky background with gentle atmospheric wind trails",
     "dozens of hand-drawn calendar pages with dates flying upward into the night sky in a graceful swirling arc"),

    (99, "generations,",
     "Family tree diagram connecting ancient stick figures down to modern humans",
     "none",
     "vintage parchment genealogical chart background",
     "comic family tree diagram showing lineages of stick figures holding hands across epochs, connected by glowing golden threads"),

    (100, "those extra hours literally made",
     "Stick figures using bonus evening hours to craft tools, carve bones, and weave",
     "front",
     "cozy firelit hearth with stone tools and hides arranged on ground",
     "two stick figures by fire: one flintknapping an arrowhead, one stitching hide, both with round white heads and two focused black dot eyes"),

    (101, "us who we are.",
     "A modern stick figure and an ancient hunter stick figure fist-bumping by fire",
     "front",
     "split temporal background: ancient cave on left, modern apartment on right, unified by fire",
     "ancient hunter stick figure and modern hoodie-wearing stick figure giving each other a friendly fist bump across time, both with two happy black dot eyes"),

    (102, "In 2014,",
     "A modern academic journal cover with bold year '2014' stamped on front",
     "none",
     "clean scientific university library desk background",
     "scholarly journal volume open on wooden desk with crisp black text, prominent '2014' date, and official university emblem doodle"),

    (103, "anthropologist Polly Wiessner",
     "Portrait illustration of anthropologist Polly Wiessner with field hat and notebook",
     "front",
     "African research field camp background with tents and desert horizon",
     "female anthropologist stick figure wearing brimmed sun hat, khaki vest, holding research ledger, two intelligent observant black dot eyes and warm smile"),

    (104, "published a legendary study",
     "Prestigious scientific paper with bold title and gold award ribbon seal",
     "none",
     "clean white desk surface with reading lamp glow",
     "formal academic paper with title 'Embers of Society' displayed prominently, adorned with a golden prize rosette ribbon and laurels"),

    (105, "in the Proceedings of the",
     "Official cover of PNAS journal with bold scientific seal emblem",
     "none",
     "prestigious scientific archive bookshelf background",
     "cover of 'Proceedings of the National Academy of Sciences' with bold serif lettering and intricate academic crest doodle"),

    (106, "National Academy of Sciences.",
     "Classic Greek revival neoclassical scientific academy building doodle",
     "none",
     "clean educational background with stately columns and pediment",
     "hand-drawn classical architectural facade with stone pillars, triangular pediment, and engraved text 'National Academy of Sciences'"),

    (107, "She spent years analyzing",
     "Researcher stick figure sitting discreetly with audio recorder near Bushmen",
     "side",
     "Kalahari desert camp at dusk with traditional grass shelters",
     "researcher stick figure in side profile sitting quietly on low stool with vintage tape recorder and microphone, single focused black dot eye"),

    (108, "conversations among the",
     "Comic speech bubbles floating from a group of villagers chatting warmly",
     "none",
     "desert clearing at dusk with warm earth tones",
     "colorful hand-drawn comic speech bubbles of varying sizes floating up from a circle of campsite dwellers, filled with speech squiggles and laughing emojis"),

    (109, "Ju/'hoansi Bushmen",
     "Group of Ju/'hoansi Bushmen stick figures gathered in peaceful circle in desert",
     "front",
     "wide Kalahari desert landscape with red sand dunes and dry thorn bushes",
     "four traditional Bushmen stick figures in beaded headbands and leather aprons, sitting in a circle, each with two expressive black dot eyes and animated faces"),

    (110, "in the Kalahari Desert -",
     "Vast sweeping red sand dunes of the Kalahari under expansive African sky",
     "none",
     "panoramic desert vista with rolling red sand dunes and lone acacia tree silhouette",
     "breathtaking wide landscape of rippling Kalahari red sand ridges stretching toward the horizon under a pale violet evening sky"),

    (111, "one of the last groups",
     "Isolated desert encampment glowing like a tiny beacon of humanity in vast desert",
     "none",
     "vast aerial view of Kalahari desert at twilight",
     "small cluster of traditional thatch huts and a solitary glowing hearth in the center of an immense untouched wilderness expanse"),

    (112, "on the planet living the",
     "Stick figure foraging naturally with digging stick in untouched nature",
     "side",
     "untamed desert scrubland with wild tubers and thorny shrubs",
     "hunter-gatherer stick figure in side profile carefully digging for roots with a fire-hardened wooden stick, single attentive black dot eye"),

    (113, "original human lifestyle.",
     "Ancient lifestyle tableau: tracking footprints, harvesting wild nuts, living free",
     "front",
     "open natural landscape free of modern roads, wires, or buildings",
     "two stick figures walking together across open terrain with leather pouch bags, completely in tune with nature, both with two calm black dot eyes"),

    (114, "And what she found was hilarious.",
     "Anthropologist stick figure chuckling behind clipboard with amused expression",
     "front",
     "field camp tent interior with lantern light on notes",
     "anthropologist stick figure holding field notebook, chuckling with hand over mouth, two squinting joyful black dot eyes, and curved laughing eyebrows"),

    (115, "During the day,",
     "Harsh bright daytime sun beating down on stick figures doing manual labor",
     "front",
     "dry desert savannah under blazing noon sun with heat mirage waves",
     "two stick figures sweating under blinding sun, carrying firewood and digging sticks, with tired drooping black dot eyes and weary postures"),

    (116, "about eighty percent of all",
     "Large pie chart showing 80% dominant blue slice labeled 'Work & Logistics'",
     "none",
     "clean paper chart background with neat margins",
     "bold pie chart graphic where eighty percent of the circle is filled with deep blue labeled '80% Practical Work Talk', with tiny sliver for stories"),

    (117, "chatter was pure workplace small talk.",
     "Two prehistoric stick figures standing awkwardly like office watercooler chat",
     "front",
     "prehistoric desert scrub with a hollow baobab tree like an office watercooler",
     "two stick figures standing stiffly with hands on hips, mimicking awkward office small talk, both with two blank neutral black dot eyes"),

    (118, "Who's hunting what?",
     "Stick figure pointing toward horizon questioning another hunter with bow",
     "side",
     "open savannah with animal tracks in the red dirt",
     "stick figure in side profile with spear asking question, second stick figure with bow shrugging with single questioning black dot eye"),

    (119, "Are those roots poisonous?",
     "Stick figure holding a suspicious squiggly root with big question mark",
     "front",
     "desert clearing with digging basket and dug-up tubers",
     "stick figure holding a bizarre knobby purple root at arm's length, inspecting it with two skeptical cross-eyed black dot eyes and crooked frown"),

    (120, "Who borrowed my favorite spear?",
     "Angry stick figure looking around empty spear rack with hands threw in air",
     "front",
     "campsite with wooden weapon rack showing one missing spear slot",
     "frustrated stick figure with arms thrown high in dramatic exasperation, two wide furious black dot eyes, open complaining mouth, and empty weapon stand"),
]

