"""
Storyboard Visual Data: Part 2 (Shots 121 - 240)
Project: 2- What Did Ancient Humans Do at Night
"""

SHOTS_PART_2 = [
    # --- ACT 3 CONTINUED: THE CAMPFIRE COMEDY CLUB & STORYTELLING (121 - 150) ---
    (121, "Economic bickering,",
     "Two prehistoric stick figures aggressively bartering flint knives and bone beads",
     "front",
     "daytime campsite background with animal hides spread out for trading",
     "two stick figures leaning across trading blanket gesturing indignantly, one holding flint knife, one holding beads, both with two squabbling black dot eyes"),

    (122, "logistics,",
     "Stick figure pointing with wooden stick at animal migration map drawn in dirt",
     "side",
     "sandy ground clearing with stick-drawn route lines and mountain doodles",
     "stick figure in side profile squatting down pointing a stick at ground drawings, single focused black dot eye and serious mouth"),

    (123, "and complaining about the weather.",
     "Stick figure wiping sweat from forehead glaring up at scorching cloudless sun",
     "front",
     "parched desert ground with heat waves rising under blinding white sky",
     "stick figure wiping brow with back of hand, tongue out, looking up at blazing cartoon sun with two irritated squinting black dot eyes"),

    (124, "Daytime talk was work.",
     "Prehistoric spreadsheet stone tablet with checkmarks and tally marks",
     "none",
     "clean paper background with stone slab texture",
     "heavy stone slab carved with neat rows of prehistoric tally marks, checkmark doodles, and spear icons, resembling an ancient Excel sheet"),

    (125, "But once darkness fell",
     "Sun setting as deep blue twilight washes over the desert camp",
     "none",
     "Kalahari landscape with sun dipping below horizon and first evening stars appearing",
     "serene twilight transition as cool blue and purple shadows gently blanket the red sand dunes, bringing relief from the day's heat"),

    (126, "and everyone huddled around the campfire,",
     "Circle of stick figures gathering closely around the warm central hearth",
     "front",
     "nocturnal desert clearing with glowing campfire in center and night sky above",
     "five stick figures seated in a tight circle around glowing orange flames, all with round white heads and two warm friendly black dot eyes"),

    (127, "the entire vibe shifted.",
     "Campfire lighting transforming from mundane camp into a magical glowing arena",
     "none",
     "warm circular campfire aura surrounded by soft dark night",
     "dramatic comic shift: glowing golden light envelops the camp, stylized musical notes and laugh doodle icons floating upward into the dark"),

    (128, "Over eighty-one percent of",
     "Infographic pie chart showing massive 81% golden slice labeled 'Stories & Myths'",
     "none",
     "clean parchment background with clean comic typography",
     "large circular pie chart where eighty-one percent is glowing warm orange with open book and comedy mask doodles labeled '81% Storytelling'"),

    (129, "conversations suddenly turned",
     "Stick figures leaning forward in rapt attention around the fire",
     "side",
     "warmly lit campfire circle with dancing flame shadows on ground",
     "two stick figures in side profile leaning forward with chins resting in palms, single fascinated wide black dot eye on each, mesmerized by the speaker"),

    (130, "into epic storytelling: heroic myths,",
     "Stick figure elder dramatically acting out a battle with a legendary giant beast",
     "front",
     "campfire glowing brightly with giant monster shadow cast on background rocks",
     "animated stick figure standing with raised spear casting an enormous heroic shadow against the rock, two fierce expressive black dot eyes"),

    (131, "scandalous gossip from distant camps,",
     "Two stick figures whispering behind hands with mischievous gossiping expressions",
     "side",
     "cozy campfire edge with flickering warm shadows",
     "two stick figures in side profile leaning in close, one cupping hand to other's ear, both with mischievous twinkling black dot eyes and sneaky smiles"),

    (132, "ghost stories,",
     "Spooky campfire scene: stick figure holding glowing ember under chin making monster face",
     "front",
     "dark nocturnal camp with eerie upward fire illumination",
     "stick figure holding glowing torch below chin casting spooky upward shadows, two wide bulging spooky black dot eyes, surrounded by comic ghost doodles"),

    (133, "and jokes that had the whole",
     "Stick figure comedian by fire delivering a punchline with animated hand pose",
     "front",
     "central campfire with sparks leaping playfully into air",
     "charismatic stick figure standing by fire gesturing with open arms, two cheerful wink-like black dot eyes, delivering a hilarious punchline"),

    (134, "tribe crying with laughter.",
     "Group of stick figures rolling on the ground laughing hysterically with tears streaming",
     "front",
     "sand ground beside fire with flying comic laughter tears",
     "three stick figures clutching their bellies, tears streaming from tightly squeezed crescent laughing eyes, mouths wide open in roaring laughter"),

    (135, "Wiessner realized the campfire",
     "Anthropologist stick figure observing the scene with a moment of pure realization",
     "front",
     "outer edge of campsite in soft shadows holding open ledger",
     "anthropologist stick figure smiling warmly with glowing lightbulb over head, two enlightened black dot eyes, writing note with fountain pen"),

    (136, "wasn't just a heat source -",
     "A simple wood fire with thermometer doodle turning into a neon stage sign",
     "none",
     "split conceptual background: basic campfire on left, glowing theater marquee on right",
     "stylized transformation where crackling campfire embers morph into the glowing neon marquee lights of a vintage entertainment stage"),

    (137, "it was humanity's very first",
     "Ancient cave wall framed with comic theater curtains doodle",
     "none",
     "red velvet comic stage curtains opening to reveal an ancient cave campfire",
     "hand-drawn theater stage curtains tied back on both sides, framing a crackling prehistoric campfire like a grand Broadway production"),

    (138, "comedy club,",
     "Prehistoric stick figure standing before a carved stone microphone by fire",
     "front",
     "brick-textured cave wall backdrop like a modern stand-up comedy club",
     "stick figure standing in spotlight holding a stone microphone on a bone stand, two expressive joking black dot eyes, and a confident stand-up smirk"),

    (139, "our first classroom,",
     "Stick figure teacher pointing at star constellations with a group of stick figure students",
     "front",
     "open clearing under starry sky with chalkboard doodle on cave wall",
     "elder stick figure holding pointer stick teaching young stick figures, all with round white heads, two attentive black dot eyes looking up at sky"),

    (140, "and our first cinema.",
     "Stick figures watching dynamic animated animal shadows dancing on cave wall",
     "back",
     "dark cave interior with firelight casting dancing mammoth shadows on stone wall",
     "row of stick figures seen from behind (back pose) watching majestic hand-shadow mammoths and hunters on the wall, zero facial features visible"),

    (141, "Beside glowing coals,",
     "Close-up of bright orange coals pulsing with heat in a neat stone ring",
     "none",
     "dark earthen hearth floor with gray ash and glowing crimson coals",
     "intimate macro view of incandescent campfire coals with delicate glowing veins of orange heat and curling white smoke wisps"),

    (142, "humans learned to stop obsessing",
     "Crossed-out thought bubble showing repetitive wild berries and nuts",
     "none",
     "clean paper background with gentle vignette",
     "comic thought bubble packed with mundane repetitive drawings of wild red berries and seeds, crossed out with a bold friendly red ink 'X'"),

    (143, "over berries and start imagining",
     "Stick figure gazing into night sky as glowing constellations transform into mythological heroes",
     "front",
     "deep blue night sky with glowing starry constellations overhead",
     "stick figure resting on elbows looking up in wonder, two dreamy wide black dot eyes, as starry lines form a magnificent soaring eagle constellation"),

    (144, "things that didn't exist yet.",
     "Whimsical doodles of mythical creatures: flying winged bison and glowing spirits",
     "none",
     "ethereal starry night sky background with soft glowing dust",
     "playful hand-drawn comic doodles of a winged flying bison, an ancient celestial spirit, and fantastic mythological heroes floating across the sky"),

    (145, "It's where human culture was born.",
     "Tree of human culture sprouting from a glowing campfire hearth",
     "none",
     "rich textured parchment background with roots sinking into soil",
     "majestic hand-drawn tree sprouting directly from the campfire flames, branches labeled with ink banners: 'Myth', 'Music', 'Humor', 'Language'"),

    (146, "But the night wasn't just an",
     "Stick figure wearing fur pelt holding stone popcorn bowl watching shadows",
     "front",
     "cozy cave living room with stone recliner and flickering firelight",
     "humorous stick figure sitting on a stone chair eating from a clay bowl labeled 'Cave Corn', two entertained black dot eyes and grinning mouth"),

    (147, "ancient Netflix session around the coals.",
     "Humorous stone-age TV screen carved from rock showing dancing animal shadows",
     "none",
     "limestone cave wall with TV antenna doodle made of crossed wooden bones",
     "flat rectangular stone slab shaped like a modern flatscreen TV with rabbit-ear bone antennas, displaying a flickering campfire silhouette"),

    (148, "Something even weirder was",
     "A giant glowing question mark hovering mysteriously above a sleeping stick figure",
     "front",
     "dim nocturnal cave with soft ambient blue moonlight on sleeping furs",
     "stick figure sleeping peacefully while a large translucent spiral question mark glows overhead, two simple sleeping dash-line eyes"),

    (149, "happening with their sleep -",
     "Brain diagram showing glowing sleep waves transitioning between stages",
     "none",
     "clean scientific textbook background with EEG brainwave graph",
     "cross-section diagram of human brain with pulsing wavy ink lines and clock icons, showing natural cyclic sleep rhythms"),

    (150, "something science only",
     "Laboratory microscope and stack of modern sleep research papers",
     "none",
     "clean scientific laboratory workbench with subtle technical grid",
     "modern brass microscope resting beside a thick stack of sleep research manuscripts stamped with university logos"),

    # --- ACT 4: THE SLEEP SECRET: BIPHASIC SLEEP (151 - 212) ---
    (151, "rediscovered thirty years ago.",
     "Calendar showing '1990s' with modern scientists examining ancient parchment",
     "none",
     "clean archival study background with desk lamp and historical timeline",
     "retro calendar page showing the 1990s turning over, beside a magnifying glass resting on aged medieval sleep manuscripts"),

    (152, "Turns out,",
     "Lightbulb illuminating over an open ancient leather-bound diary",
     "none",
     "dark library desk with glowing ambient illumination",
     "open antique leather diary with yellowed deckle-edge pages, a bright comic lightbulb bursting into light directly above the open spread"),

    (153, "your body was never actually",
     "Anatomical stick figure human body blueprint with biological gears",
     "front",
     "clean technical blueprint paper with white drafting grid lines",
     "stick figure silhouette drawn on cyan blueprint paper with internal clock gears ticking, two neutral analytical black dot eyes"),

    (154, "designed to sleep",
     "A comfortable bed with fluffy pillows and duvet under a night window",
     "none",
     "quiet bedroom interior at night with wooden bed frame and starry window",
     "neatly made bed with inviting crumpled blankets and plump pillows, bathed in calm silver moonlight from an open window"),

    (155, "in one solid eight-hour marathon.",
     "A heavy 8-hour concrete block crushing a fragile alarm clock",
     "none",
     "clean paper background with cracked floor doodles",
     "humorous solid concrete rectangular block labeled '8 SOLID HOURS' slamming down and squishing a tiny ticking alarm clock flat"),

    (156, "In 2001,",
     "Library archive drawer opening with year tag '2001' clearly marked",
     "none",
     "wooden library catalog cabinet with brass drawer pulls",
     "close-up of an antique library card catalog drawer pulled open, labeled '2001', overflowing with handwritten index cards"),

    (157, "historian Roger Ekirch dropped a",
     "Portrait of historian Roger Ekirch in tweed jacket holding historical manuscript",
     "front",
     "warm historic library interior with towering bookshelves and ladder",
     "historian stick figure wearing glasses and tweed vest, holding open historical ledger, two scholarly observant black dot eyes and gentle smile"),

    (158, "bombshell paper after spending",
     "Academic manuscript with comic explosion impact lines and confetti sparks",
     "none",
     "scholarly study desk with scattered reference papers",
     "academic journal open to title page 'At Day's Close: Night in Times Past', bursting with comical starburst energy and flying sparks"),

    (159, "sixteen years digging through",
     "Stick figure historian knee-deep in massive stacks of dusty medieval books",
     "front",
     "monumental library archive with towering leaning book stacks reaching ceiling",
     "historian stick figure sitting on floor surrounded by mountains of leather-bound folios, two wide enthusiastic black dot eyes, holding open quill diary"),

    (160, "old archives.",
     "Rows of towering ancient library shelves lined with glowing leather-bound tomes",
     "none",
     "grand atmospheric archive hall with wooden arches and dusty sunbeams",
     "dramatic perspective shot down a cavernous archival aisle with hundreds of cracked vellum folios, scroll containers, and wax-sealed boxes"),

    (161, "He found over five hundred",
     "Massive filing box labeled '500+ REFERENCES' bursting with historical documents",
     "none",
     "clean archival desk with neat organizational trays",
     "sturdy wooden archive box with brass plaque reading '500+ HISTORICAL REFERENCES', packed to the brim with yellowed parchment scrolls"),

    (162, "separate references",
     "Montage of different manuscript snippets with highlighted Latin and Old English phrases",
     "none",
     "parchment collage background with various calligraphy styles",
     "artful collage of aged paper clippings: medieval Latin gothic script, Renaissance English court handwriting, and French letters"),

    (163, "across centuries -",
     "Winding historic timeline ribbon weaving through medieval castles and Renaissance towns",
     "none",
     "clean parchment background with panoramic historical landscape silhouettes",
     "flowing golden timeline banner weaving from ancient Greek temples through medieval stone castles to 18th-century cobblestone cities"),

    (164, "from medieval court records",
     "Formal medieval parchment with wax seal and quill pen doodle",
     "none",
     "dark oak legal table with candle wax drip and quill stand",
     "aged legal parchment with elegant gothic calligraphy, a red royal wax seal stamped with lion insignia, and a raven feather quill"),

    (165, "and Latin diaries to Homer's Odyssey -",
     "Ancient Greek papyrus scroll showing Homer's Odyssey with Greek lettering",
     "none",
     "classical Mediterranean stone desk with olive branch doodle",
     "unrolled ancient papyrus scroll with Greek script, adjacent to an ink drawing of an ancient Greek sailing galley beneath starry sky"),

    (166, "all casually mentioning",
     "Highlighted manuscript line with doodle hand pointing at historical text",
     "none",
     "enlarged parchment text background with clean ink lettering",
     "close-up of antique handwritten text with a cartoon hand pointing index finger at an underlined ink phrase: 'first sleepe'"),

    (167, "something called 'first sleep'",
     "Clock graphic showing 'FIRST SLEEP: 9 PM - 1 AM' with sleeping stick figure",
     "none",
     "clean circular diagram background with deep night-sky aesthetic",
     "circular clock diagram highlighting the 9:00 PM to 1:00 AM quadrant labeled 'FIRST SLEEP' with a cozy sleeping stick figure icon"),

    (168, "and 'second sleep.'",
     "Clock graphic showing 'SECOND SLEEP: 3 AM - 7 AM' with morning dawn colors",
     "none",
     "clean circular diagram background with warm dawn gradient",
     "circular clock diagram highlighting the 3:00 AM to 7:00 AM quadrant labeled 'SECOND SLEEP' with a peaceful resting stick figure icon"),

    (169, "Before the industrial revolution,",
     "Pre-industrial countryside village with watermill and thatched cottages at dusk",
     "none",
     "bucolic countryside landscape with rolling green pastures, stone bridge, and river",
     "peaceful pre-industrial European hamlet at twilight, complete with wooden watermill, cozy thatched stone cottages, and no smoke stacks"),

    (170, "people didn't sleep",
     "Old-fashioned wooden four-poster bed with canopy and warm curtains",
     "none",
     "charming rustic cottage bedroom with exposed wooden ceiling beams and plank floor",
     "rustic wooden four-poster bed with thick linen curtains tied to posts, a warm woven wool quilt, and bedside candle on small stand"),

    (171, "in one unbroken chunk.",
     "A solid 8-hour sleep bar being sliced in half by a pair of scissors",
     "none",
     "clean paper background with measurement markers",
     "horizontal blue sleep bar labeled '8 Continuous Hours' being cleanly snipped in half by giant cartoon scissors, revealing a gap"),

    (172, "They went to bed right after sunset,",
     "Medieval stick figure in nightshirt climbing into bed as sun sets outside",
     "side",
     "cottage bedroom with cottage window showing pink sunset horizon",
     "stick figure in side profile wearing long linen nightshirt and sleeping cap, climbing into bed, single sleepy black dot eye, smiling yawningly"),

    (173, "slept for about four hours,",
     "Stick figure sleeping peacefully under patchwork quilt with '4 HOURS' clock",
     "front",
     "dim cozy bedroom bathed in moonlight with quiet shadows",
     "stick figure resting head on fluffy feather pillow, two gentle sleeping dash eyes, peaceful content smile, small clock reading '4 Hours'"),

    (174, "and then casually woke up.",
     "Stick figure sitting up in bed stretching arms and blinking calmly",
     "front",
     "quiet midnight bedroom with candle unlit on bedside table",
     "stick figure sitting up upright in bed, stretching arms wide, two calm clear black dot eyes, expression totally relaxed and unbothered"),

    (175, "They'd hang out,",
     "Medieval stick figure sitting in cozy armchair beside embers wrapped in blanket",
     "front",
     "warm stone cottage hearth room with soft glowing embers in fireplace",
     "stick figure wrapped in wool shawl sitting comfortably in wooden armchair by fireplace, two peaceful black dot eyes, sipping warm cider"),

    (176, "perfectly awake and relaxed,",
     "Close-up of stick figure's face showing deep calm serene expression",
     "front",
     "soft ambient midnight room with gentle warm glow from candle",
     "close-up of round white head with two clear serene black dot eyes, relaxed smooth eyebrows, and a tranquil gentle curved smile"),

    (177, "for an hour or two right",
     "Hourglass with sand trickling calmly through a peaceful 2-hour window",
     "none",
     "dark wood study surface with soft candlelight",
     "classic brass hourglass with fine golden sand flowing steadily through the glass waist, labeled with a friendly banner: '2 Hours of Peace'"),

    (178, "in the dead of night.",
     "Moon hanging high over a sleeping quiet medieval village under sea of stars",
     "none",
     "panoramic view of cobblestone village under crystal-clear starry midnight sky",
     "full silver moon casting serene shadows over cobblestone streets, slate rooftops, and church spire, total silence across the world"),

    (179, "Then they'd go back to sleep for",
     "Stick figure blowing out bedside candle and sliding comfortably back under quilt",
     "side",
     "dark cozy bedroom illuminated by the dying wick of a wax candle",
     "stick figure in side profile leaning over to blow out candle, single drowsy black dot eye, sliding legs under warm blankets"),

    (180, "another four hours until dawn.",
     "Stick figure sleeping deeply as golden morning light begins peeking through window",
     "front",
     "bedroom window showing soft golden sunrise light starting to touch the wall",
     "stick figure sleeping soundly on back with covers pulled up, two peaceful sleeping dash eyes, as warm morning sunbeams enter the room"),

    (181, "This wasn't insomnia.",
     "Bold red stamp 'NOT INSOMNIA' stamped cleanly over an open notebook",
     "none",
     "clean paper desk background with antique inkwell",
     "open lined journal with bold green checkmarks, overlaid with a prominent friendly red rubber stamp reading 'NOT INSOMNIA'"),

    (182, "It was just Tuesday.",
     "Humorous medieval calendar page showing regular routine 'TUESDAY: SLEEP, CHILL, SLEEP'",
     "none",
     "aged parchment calendar page with hand-drawn medieval floral borders",
     "calendar block for 'Tuesday' with neat calligraphy agenda: '1st Sleep, Midnight Contemplation, 2nd Sleep, Bake Bread', perfectly normal"),

    (183, "What did people do",
     "Stick figure standing with hands out looking curious with question mark doodles",
     "front",
     "warm vintage interior with wooden floorboards and patterned wallpaper",
     "stick figure standing with open inquiring hands, head tilted, two curious black dot eyes, surrounded by three playful question marks"),

    (184, "during that midnight recess?",
     "Clock with gears opening like a secret door revealing cozy nighttime activities",
     "none",
     "rich dark vintage library background with mechanical clockwork",
     "antique mantel clock face splitting open like double doors, revealing tiny comic vignettes of reading, writing, and tea sipping inside"),

    (185, "Literally whatever they wanted.",
     "Collage of stick figures doing various peaceful midnight activities happily",
     "front",
     "cozy nighttime cottage with split multi-panel layout",
     "four stick figures in separate panels: one reading book, one writing letter, one petting cat, one staring at stars, all with happy black dot eyes"),

    (186, "A sixteenth-century French",
     "Vintage ornate French medical treatise title page with fleur-de-lis crest",
     "none",
     "classic 16th-century typography layout on yellowed laid paper",
     "ornate woodcut book border featuring royal French crest, Latin motto, and bold typography reading 'Traité Médical - Paris, 1580'"),

    (187, "doctor legitimately wrote",
     "Distinguished Renaissance doctor stick figure in ruffled collar holding quill",
     "front",
     "Renaissance study with wooden desk, skull memento mori, and globe",
     "doctor stick figure wearing puffy black doublet and white ruffled neck collar, holding quill pen, two wise black dot eyes and stately beard doodle"),

    (188, "that this was the best time for",
     "Doctor stick figure winking with a knowing smile pointing at a manuscript page",
     "side",
     "candlelit doctor's chamber with anatomy drawings on wall",
     "doctor stick figure in side profile winking with single mischievous black dot eye, pointing pen at medical text, nodding with subtle grin"),

    (189, "couples to make babies",
     "Cozy bed behind sheer privacy curtains with two pairs of feet sticking out happily",
     "none",
     "warm candlelit cottage bedroom with soft velvet bed curtains",
     "romantic four-poster bed with sheer curtains drawn, comic floating hearts overhead, and two pairs of cartoon feet wiggling happily at the foot"),

    (190, "because they were well-rested",
     "Battery meter doodle showing full 100% green energy icon over cheerful couple",
     "none",
     "clean parchment background with humorous energy gauge",
     "comic battery icon glowing vibrant green at full '100% ENERGY' capacity, radiating cheerful vitality lines and little spark doodles"),

    (191, "and enthusiastic.",
     "Two stick figures smiling warmly holding hands by candlelight in bedroom",
     "front",
     "warm candlelit bedroom with wooden nightstand and gentle shadows",
     "two stick figures sitting on edge of bed holding hands warmly, each with two sparkling happy black dot eyes and affectionate smiles"),

    (192, "Other people visited their neighbors,",
     "Stick figure holding lantern walking across dark village path to neighbor's house",
     "side",
     "cobblestone medieval lane under starry sky with lit windows",
     "stick figure in side profile in coat carrying a glowing tin lantern, knocking on neighbor's cottage door, single friendly black dot eye"),

    (193, "interpreted their weird dreams",
     "Stick figure sitting in bed scribbling in notebook with floating dream cloud",
     "side",
     "dim midnight bedroom with candle on wooden nightstand",
     "stick figure in side profile sitting up writing in dream journal, single focused black dot eye, thought bubble showing a fish wearing a top hat"),

    (194, "while they were fresh,",
     "Thought bubble with vivid dream doodles: floating clock, flying cat, magic tree",
     "none",
     "soft ambient dark background with pastel dream clouds",
     "ethereal comic dream cloud filled with whimsical doodles: a flying cat with wings, an upside-down clock, and a smiling crescent moon"),

    (195, "wrote poetry,",
     "Stick figure writer at desk dipping quill into ink writing rhyming verses",
     "side",
     "quiet midnight study with single candle flame flickering on wooden desk",
     "stick figure in side profile hunched gracefully over parchment dipping feather quill into inkwell, single inspired black dot eye and poetic smile"),

    (196, "or just chilled in bed",
     "Stick figure propped up on three pillows in bed looking totally peaceful",
     "front",
     "cozy four-poster bed with soft linen pillows and warm ambient darkness",
     "stick figure propped comfortably on fluffy pillows with hands folded across chest, two serene black dot eyes, enjoying the pure calm"),

    (197, "and thought about life.",
     "Stick figure staring out starry window with philosophical gentle expression",
     "front",
     "bedroom window opening out into vast deep night sky with Milky Way",
     "stick figure standing at open window looking out at stars, chin in hand, two deep contemplative black dot eyes, completely unhurried"),

    (198, "Medical manuals from the 1500s",
     "Ancient leather-bound book open on wooden bookstand with engraved anatomical sketch",
     "none",
     "dark wood library table with brass clasps and open folio",
     "heavy 16th-century leather medical volume open on oak bookstand with woodcut diagrams of the human circadian rhythm and sleep phases"),

    (199, "actually called this window 'the watch' -",
     "Ornate calligraphy banner reading 'THE WATCH' with pocket watch doodle",
     "none",
     "vintage parchment page with illuminated gothic lettering",
     "magnificent illuminated medieval banner in deep red and black ink reading 'THE WATCH', framed by an antique pocket watch doodle"),

    (200, "the ultimate quiet hour",
     "Stick figure sitting in center of silent dark room with soundwave meter at zero",
     "front",
     "tranquil room with soft ambient moonlight and zero visual clutter",
     "stick figure sitting peacefully in lotus position on rug, two closed peaceful dash-line eyes, soundwave gauge flatlining at absolute zero decibels"),

    (201, "when the world was asleep",
     "Sleeping town with little 'Zzz' clouds rising from every chimney under the moon",
     "none",
     "panoramic view of rooftops, chimneys, and church towers under starry sky",
     "peaceful sleeping townscape at night, delicate hand-drawn 'Zzz' bubbles floating gently from chimney tops into the starlit sky"),

    (202, "and your brain was completely unbothered.",
     "Stick figure brain meditating happily inside skull surrounded by zen pebbles",
     "front",
     "clean minimal background with soft calming blue tones",
     "cartoon human brain character sitting cross-legged in zen meditation, two happy closed curved eyes, balanced atop a stack of smooth pebbles"),

    (203, "For centuries,",
     "Sandglass with centuries of sand piled high beneath an antique calendar",
     "none",
     "dark study shelf with rows of historical chronologies",
     "tall antique hourglass surrounded by stacked historical volumes spanning the 1600s, 1700s, and 1800s"),

    (204, "modern historians read these",
     "Modern historian stick figure in tweed jacket reading old diary at modern desk",
     "side",
     "contemporary university office with fluorescent lamp and laptop",
     "modern historian stick figure in side profile wearing spectacles, reading antique manuscript, single skeptical black dot eye and cocked eyebrow"),

    (205, "diaries and thought,",
     "Thought bubble over historian reading 'Just poetic license!' with chuckle",
     "none",
     "university office background with academic diploma on wall",
     "comic thought bubble with text 'Oh, just a charming poetic metaphor!', dismissive wave gesture doodle"),

    (206, "'Haha,",
     "Historian stick figure laughing dismissively while waving hand at book",
     "front",
     "academic study with computer screen showing modern 9-to-5 calendar",
     "historian stick figure chuckling dismissively with hand waving away the text, two squinting amused black dot eyes and smug smirking mouth"),

    (207, "what a cute metaphor,",
     "Quotation marks framing cartoon stick figures dreaming of first and second sleep",
     "none",
     "clean paper background with decorative curly quotes",
     "large stylized quotation marks framing a cute doodle of stick figures sleeping twice, treated as folklore fantasy by modern academics"),

    (208, "' because we literally couldn't",
     "Modern office worker stick figure trapped inside a rigid square calendar box",
     "front",
     "stark modern corporate office background with fluorescent light grid",
     "stick figure wearing necktie physically trapped inside a rigid black box labeled '8-Hour Sleep Block', two confused stressed black dot eyes"),

    (209, "comprehend sleeping differently",
     "Stick figure scratching head looking baffled at an unconventional clock",
     "front",
     "modern minimalist room with sleek digital clock",
     "stick figure standing with hand scratching head, staring at a bizarre two-phase clock, two perplexed black dot eyes and crooked wavy mouth"),

    (210, "than an office worker.",
     "Row of identical corporate stick figures marching with briefcases in lockstep",
     "side",
     "monotonous corporate office hallway with cubicle partitions",
     "three identical modern stick figures in side profile marching in perfect rigid sync carrying black briefcases, single blank black dot eye on each"),

    (211, "Translators even mangled ancient",
     "Vintage Latin dictionary with words crossed out and rewritten with red pen",
     "none",
     "clean wooden translation desk with ink eraser bottle",
     "open bilingual Latin-English lexicon with original words aggressively crossed out in red ink and replaced with modern anachronistic terms"),

    (212, "Greek and Latin just to make",
     "Classical Greek scroll being forced through a square modern paper shredder",
     "none",
     "clean editorial background with shredder machine",
     "classical papyrus scroll covered in Greek lettering being humorously fed into a modern paper shredder labeled 'Modern Biased Translation'"),

    (213, "ancient people sound like modern",
     "Greek philosopher stick figure in toga holding a modern smartphone and coffee cup",
     "front",
     "classical Greek temple ruins blending awkwardly into modern corporate office",
     "comic ancient Greek stick figure in toga and laurel wreath holding a disposable Starbucks coffee cup, two deadpan black dot eyes"),

    (214, "nine-to-fivers.",
     "Ancient Spartan stick figure punching an electric timeclock with punchcard",
     "side",
     "stone temple courtyard with an industrial mechanical timeclock bolted to pillar",
     "Spartan warrior stick figure in helmet in side profile sliding punchcard into a modern industrial timecard machine, single bored black dot eye"),

    (215, "But then real science proved the",
     "A modern scientific test tube and beaker breaking through old history textbooks",
     "none",
     "clean laboratory counter with glass beakers and measuring pipettes",
     "gleaming scientific Erlenmeyer flask with glowing blue liquid shattering an old dusty textbook labeled 'Assumptions', comic impact lines"),

    (216, "diaries right.",
     "A glowing golden checkmark stamped over an open antique leather diary",
     "none",
     "clean parchment desk with soft morning light",
     "historic open diary page with a bold vibrant green checkmark stamped firmly over the text 'first and second sleep'"),

    # --- ACT 5: SCIENTIFIC REDISCOVERY: THOMAS WEHR'S EXPERIMENT (217 - 253) ---
    (217, "In 1992,",
     "Calendar page tearing off to reveal bold year '1992' with clinical logo",
     "none",
     "clean laboratory wall background with 1990s aesthetic",
     "tear-off calendar block displaying bold numbers '1992', beside the official logo of the National Institute of Mental Health"),

    (218, "psychiatrist Thomas Wehr",
     "Portrait of psychiatrist Thomas Wehr in lab coat with clipboard and stethoscope",
     "front",
     "modern clinical research laboratory with monitoring screens in background",
     "psychiatrist stick figure wearing white doctor's lab coat, holding clipboard and pen, two intelligent focused black dot eyes and warm reassuring smile"),

    (219, "at the National Institute of",
     "Modern scientific research campus building with glass windows and manicured lawn",
     "none",
     "clean architectural facade background with blue sky",
     "modern research institute brick and glass building with formal stone entrance sign reading 'National Institute of Mental Health'"),

    (220, "Mental Health ran a wild experiment.",
     "Laboratory control room with multiple monitor screens showing volunteer sleep rooms",
     "none",
     "dark scientific observation room with glowing computer screens and waveform graphs",
     "control console with glowing monitors displaying live EEG waveforms, sleep chamber camera feeds, and digital status bars"),

    (221, "He took a bunch of normal",
     "Group of everyday stick figure volunteers standing in line smiling politely",
     "front",
     "bright clinical waiting room with chairs and potted plant",
     "four diverse stick figure volunteers in casual clothes standing in line, all with round white heads, two curious friendly black dot eyes"),

    (222, "volunteers and took away all",
     "Scientist stick figure collecting modern gadgets: smartphones, watches, flashlights",
     "side",
     "clinical intake desk with large plastic storage bin labeled 'FORBIDDEN LIGHTS'",
     "scientist stick figure in side profile confiscating phones, digital watches, and lightbulbs into a bin, single efficient black dot eye"),

    (223, "artificial light.",
     "Lightbulb with a giant black padlock locked around the socket",
     "none",
     "dark clinical background with warning tape border",
     "large comic incandescent lightbulb encased in heavy iron chains with a sturdy padlock snapped shut, light completely extinguished"),

    (224, "For an entire month,",
     "Calendar grid showing 30 consecutive days each marked with a dark moon icon",
     "none",
     "clean paper wall calendar with neat rows of date squares",
     "calendar page for a full month where every single day box is stamped with a dark navy crescent moon symbol and 'DAY 1' to 'DAY 30'"),

    (225, "they lived in fourteen hours of",
     "Circular 24-hour clock showing massive 14-hour deep dark segment",
     "none",
     "clean clinical diagram background with concentric time rings",
     "large circular dial with a 14-hour continuous black section from 6:00 PM to 8:00 AM labeled '14 HOURS MANDATORY DARKNESS'"),

    (226, "darkness every single night,",
     "Volunteer stick figure lying in pitch-black soundproof sleep chamber",
     "front",
     "dark clinical sleep room with padded walls and bed",
     "stick figure lying comfortably in bed in darkness, two calm open black dot eyes looking around peacefully with zero anxiety"),

    (227, "exactly like our ancestors did.",
     "Split screen: modern volunteer in dark room mirroring ancient caveman in cave",
     "front",
     "split composition: modern bedroom on left, prehistoric stone shelter on right",
     "modern stick figure on left and ancient hunter stick figure on right, both resting in identical peaceful postures, both with two calm black dot eyes"),

    (228, "Within a few weeks,",
     "Time-lapse clock spinning with calendar dates flipping rapidly",
     "none",
     "clinical research observation window background with soft blue lighting",
     "dynamic comic graphic of clock hands spinning rapidly, calendar sheets floating away, representing the passage of three weeks"),

    (229, "without anyone telling them what to do,",
     "Empty instruction chalkboard with zero rules or commands written",
     "none",
     "clean laboratory study wall with empty whiteboard",
     "blank laboratory chalkboard with a single question mark, illustrating that the volunteers received zero instructions or prompting"),

    (230, "every single person naturally",
     "All four volunteer stick figures in their separate rooms sleeping in identical rhythm",
     "front",
     "four-quadrant clinical monitor display showing four identical rooms",
     "four separate monitor screens showing each volunteer in identical peaceful poses, each with round white head and relaxed expressions"),

    (231, "fell into the exact same",
     "Four identical sleep graph curves aligning in perfect harmony",
     "none",
     "clean scientific graph paper with synchronized colored curves",
     "scientific chart showing four distinct volunteer data lines locking into an identical synchronized rhythmic wave pattern"),

    (232, "pattern: four hours of sleep,",
     "Volunteer stick figure sleeping peacefully for 4 hours with 'PHASE 1' label",
     "front",
     "quiet dark sleep chamber with monitoring wire leads on head",
     "stick figure sleeping on side under clean white sheet, two peaceful closed dash eyes, accompanied by clean label 'Phase 1: 4 Hours Rest'"),

    (233, "a two-hour peaceful midnight",
     "Volunteer stick figure sitting up in bed calmly meditating in soft darkness",
     "front",
     "dark clinical room with faint indicator LED on wall casting soft twilight",
     "stick figure sitting cross-legged on bed, perfectly awake, two clear tranquil black dot eyes, gentle calm smile, zero tossing and turning"),

    (234, "waking window,",
     "Graphic showing 2-hour bridge between two mountains of sleep",
     "none",
     "serene cosmic landscape background with soft ambient glowing bridge",
     "two mountain peaks labeled 'First Sleep' and 'Second Sleep', connected by a gentle glowing golden bridge labeled 'The 2-Hour Watch'"),

    (235, "and four more hours of sleep.",
     "Volunteer stick figure sliding back into deep second sleep until morning",
     "front",
     "clinical sleep room with dawn simulation light beginning to glow softly",
     "stick figure peacefully asleep on pillow, covers tucked snugly, two closed sleeping dash eyes, label 'Phase 2: 4 Hours Rest'"),

    (236, "Their brains just booted up the",
     "Computer monitor showing a retro brain booting up with loading bar at 100%",
     "none",
     "retro 1990s computer terminal screen with green phosphor text",
     "computer CRT monitor displaying a vector wireframe human brain with a loading bar reading 'SYSTEM RESTORE: 100% FACTORY SETTINGS'"),

    (237, "original factory settings.",
     "Stick figure with a tiny golden 'FACTORY RESET OK' badge on chest",
     "front",
     "clean minimal background with soft ambient lighting",
     "stick figure standing proudly with thumbs up, two bright clear black dot eyes, wearing a shiny green seal reading 'ORIGINAL HUMAN BIOLOGY'"),

    (238, "And when Wehr tested their blood",
     "Scientist stick figure holding up a test tube of blood to the light",
     "side",
     "modern clinical chemistry laboratory with centrifuge and test tube racks",
     "scientist stick figure in side profile wearing safety goggles holding a glass vial of blood, single analytical black dot eye examining liquid"),

    (239, "chemistry during",
     "Complex chemical molecular structure diagram of the prolactin hormone",
     "none",
     "clean molecular biology grid background with chemical bonds",
     "detailed vector chemical structure diagram showing interconnected carbon rings and atoms labeled with molecular formula for prolactin"),

    (240, "that midnight waking window,",
     "Clock displaying '02:00 AM' with an illuminated chemical test vial glowing beside it",
     "none",
     "clinical laboratory counter at 2:00 AM under dim night lighting",
     "digital bench clock glowing '02:00 AM', beside a laboratory test tube glowing with vibrant golden luminescence, signifying hormone surge"),
]

