"""
Script Spinner & Intelligent Rephrasing Engine for Ink Explainer Studio
Author: Google DeepMind Antigravity System
Purpose:
  Transforms ingested reference postmortem transcripts into 100% unique,
  witty, humorous, retention-optimized explainer scripts (Casually Explained & MinutePhysics style).
  Preserves core thesis, 7-act story progression, historical/scientific facts,
  numbers, and citations while creating completely fresh, entertaining phrasing.
"""

import os
import re
from typing import Optional, Dict

# High-retention witty/humorous spun master scripts for reference videos
REFERENCE_SPUN_SCRIPTS: Dict[str, str] = {
    "What Did Ancient Humans Do at Night": """Later tonight, you're going to walk into a room, flick a tiny piece of plastic on the wall, and boom - instant artificial sun. You won't think about it. You might even complain that the bulb is slightly too warm for your aesthetic. But for ninety-nine point nine percent of human history, that switch didn't exist. When the sun went down, the entire planet turned into a sensory deprivation chamber. You couldn't see your own hand in front of your face, let alone whatever sharp object was waiting to destroy your toe. Today, true darkness is something you only experience during a power outage or inside an expensive escape room. But for over three hundred thousand years, every single one of your ancestors spent roughly half of their entire earthly existence in pitch-black nothingness. No flashlights. No scented candles. Just a giant void, a bunch of distant stars, and whatever sad little embers they managed to keep from blowing away. So what on earth were they doing for all those hours? As it turns out, the answer completely redefines human sleep, storytelling, and why you're awake at three in the morning right now.

To understand any of this, we have to talk about fire. The earliest rock-solid evidence of hominids taming fire comes from Wonderwerk Cave in South Africa, about one million years ago. But fire wasn't just ancient central heating. It completely broke and rebuilt the human schedule. Before fire, our ancestors were basically helpless primates with zero night vision. Once dusk hit, you scrambled up a tree, curled into an anxious little ball, and prayed you didn't sneeze. Wandering around in the dark was essentially volunteering to be a midnight snack. Compared to leopards, hyenas, and wolves - who basically had built-in night-vision goggles - human eyes in the dark are completely useless. Fire changed the entire food chain. A campfire creates a thirty-foot glowing dome of 'do not eat me.' Inside that circle, predators stayed away. Outside that circle, you were on the menu. This isn't hyperbole - even today, field studies show that people in modern hunter-gatherer tribes who wander away from the fire at night have a nasty habit of getting eaten. But here's the really wild part: fire didn't just save humans from becoming leopard food. It gifted them free time. Before hearths, the workday ended at sunset. That was maybe twelve hours in summer, and barely eight in winter. Fire suddenly dumped two to four bonus hours onto every single day. And over thousands of generations, those extra hours literally made us who we are.

In 2014, anthropologist Polly Wiessner published a legendary study in the Proceedings of the National Academy of Sciences. She spent years analyzing conversations among the Ju/'hoansi Bushmen in the Kalahari Desert - one of the last groups on the planet living the original human lifestyle. And what she found was hilarious. During the day, about eighty percent of all chatter was pure workplace small talk. Who's hunting what? Are those roots poisonous? Who borrowed my favorite spear? Economic bickering, logistics, and complaining about the weather. Daytime talk was work. But once darkness fell and everyone huddled around the campfire, the entire vibe shifted. Over eighty-one percent of conversations suddenly turned into epic storytelling: heroic myths, scandalous gossip from distant camps, ghost stories, and jokes that had the whole tribe crying with laughter. Wiessner realized the campfire wasn't just a heat source - it was humanity's very first comedy club, our first classroom, and our first cinema. Beside glowing coals, humans learned to stop obsessing over berries and start imagining things that didn't exist yet. It's where human culture was born.

But the night wasn't just an ancient Netflix session around the coals. Something even weirder was happening with their sleep - something science only rediscovered thirty years ago. Turns out, your body was never actually designed to sleep in one solid eight-hour marathon. In 2001, historian Roger Ekirch dropped a bombshell paper after spending sixteen years digging through old archives. He found over five hundred separate references across centuries - from medieval court records and Latin diaries to Homer's Odyssey - all casually mentioning something called 'first sleep' and 'second sleep.' Before the industrial revolution, people didn't sleep in one unbroken chunk. They went to bed right after sunset, slept for about four hours, and then casually woke up. They'd hang out, perfectly awake and relaxed, for an hour or two right in the dead of night. Then they'd go back to sleep for another four hours until dawn. This wasn't insomnia. It was just Tuesday. What did people do during that midnight recess? Literally whatever they wanted. A sixteenth-century French doctor legitimately wrote that this was the best time for couples to make babies because they were well-rested and enthusiastic. Other people visited their neighbors, interpreted their weird dreams while they were fresh, wrote poetry, or just chilled in bed and thought about life. Medical manuals from the 1500s actually called this window 'the watch' - the ultimate quiet hour when the world was asleep and your brain was completely unbothered.

For centuries, modern historians read these diaries and thought, 'Haha, what a cute metaphor,' because we literally couldn't comprehend sleeping differently than an office worker. Translators even mangled ancient Greek and Latin just to make ancient people sound like modern nine-to-fivers. But then real science proved the diaries right. In 1992, psychiatrist Thomas Wehr at the National Institute of Mental Health ran a wild experiment. He took a bunch of normal volunteers and took away all artificial light. For an entire month, they lived in fourteen hours of darkness every single night, exactly like our ancestors did. Within a few weeks, without anyone telling them what to do, every single person naturally fell into the exact same pattern: four hours of sleep, a two-hour peaceful midnight waking window, and four more hours of sleep. Their brains just booted up the original factory settings. And when Wehr tested their blood chemistry during that midnight waking window, he found something unbelievable. Their bodies were pumping out massive amounts of prolactin - the exact same bliss hormone released during meditation and after intimacy. The volunteers described feeling an almost euphoric, crystal-clear tranquility. It wasn't a sleep disorder at all - it was a completely unique state of human consciousness that our modern world completely paved over.

So what killed the midnight chill session? One word: light. In the 1600s, European cities started putting up public street lamps. Paris did it under King Louis the Fourteenth to stop muggings, and London quickly copied them. The night, which had been terrifying for millennia, suddenly became walkable. Then came cheap candles, then gas lamps in the 1800s, and then in 1879, Thomas Edison rolled out the commercial light bulb. Within a single generation, three hundred thousand years of natural night were completely erased. Even the word 'curfew' gives it away. It comes from the medieval French 'couvre-feu,' which literally means 'cover the fire.' In old towns, an evening bell would ring telling everyone to smother their hearths, because night was supposed to be dark, dangerous, and strictly meant for sleeping. In fact, walking around a medieval city after dark without holding a lantern was straight-up illegal. Night belonged to outlaws, predators, and creepy ghost stories. So naturally, humans decided to conquer it. We flooded the night with electric light, patted ourselves on the back, and called it progress.

Except we completely broke our biology in the process. Today, the average human bathes in artificial glare for seven to eight hours after sunset. And the blue light screaming from your phone screen actively bullies your brain into shutting down melatonin production. Your eyeballs can't tell the difference between TikTok and the midday sun. When high-energy photons slam into your retina at eleven at night, your brain thinks, 'Awesome, noon in July!' It delays your hormones, trashes your deep sleep, and scrambles millions of years of evolutionary rhythm. Researchers found that taking people camping for just one single week with zero screens resets their melatonin clock by two full hours, syncing them right back to sunset. That's all it takes for three hundred thousand years of ancient biology to reassert itself. We didn't just change our bedtime; we murdered an entire phase of the human mind. That peaceful, reflective midnight sanctuary between first and second sleep is gone. Instead, we have chronic insomnia, and we pop sleeping pills because we think our bodies are broken. But what if waking up at three in the morning and staring at the ceiling isn't a medical failure at all? What if that midnight stillness is just your ancient caveman brain waking up for 'the watch,' looking around for the campfire, and wondering why on earth you're stressing over emails instead of enjoying the silence? For hundreds of thousands of years, your ancestors gathered around crackling embers, shared hilarious stories, and rested in peaceful rhythms beneath a sparkling Milky Way. We traded that entire cosmic connection for an electric light switch - and we didn't even realize what we lost.""",

    "What Did Ancient Humans Do When It Rained All Week": """Imagine you haven't eaten in two days. You tracked a herd of bison yesterday, you know their exact coordinates, and all you have to do is hike out and secure dinner. And then the sky opens up. Not a refreshing little sprinkle, but an angry, sideways, wind-whipped deluge that refuses to quit. It dumps water all day, all night, and shows zero signs of clearing by tomorrow. Suddenly, your hunting trip is canceled. The mud has wiped away every footprint, running across wet rocks in bare feet is a one-way ticket to a broken ankle, and the local river is rapidly turning into an Olympic-sized moat. Worst of all, your campfire is actively hissing in agony. You aren't just bored; you are trapped. Today, a rainy weekend means throwing on oversized sweatpants, brewing hot coffee, and watching nine consecutive episodes of a true crime docuseries while feeling remarkably cozy. For you, the gentle pitter-patter on the window is essentially a natural sleeping pill. But for an ancient human fifty thousand years ago, that exact same soothing rain sound was basically an eviction notice backed by three distinct ways to die before Tuesday.

The first killer was the cold. A soaking wet human loses body heat up to twenty-five times faster than a dry one. Without waterproof Gore-Tex jackets or central heating, an extended storm at fifty degrees Fahrenheit will plunge your core temperature straight into hypothermia within hours. And virtually everywhere your ancestors lived got bitterly cold once the sun went down, even high-altitude plateaus in tropical Africa. The second threat was flash flooding. Prime cave real estate had one major design flaw: caves are almost always situated at the bottom of cliffs or right beside riverbanks. When torrential storms hit, runoff funnels straight through the living room. Modern archaeologists regularly dig up thick slabs of river sediment cemented inside ancient dwellings, marking flash floods so violent that terrified families fled and never set foot inside again. And the third threat was unexpected roommates. Humans weren't the only creatures on the savanna that despised getting drenched. Guess who else ran for the nearest dry overhang? Giant leopards, cave bears, and hyenas. In several South African caves, human fossils and prehistoric predator bones are buried in the exact same dirt layers. Some of those human skulls feature matching puncture holes that fit a leopard's canine teeth with terrifying precision. Rain compressed the entire food chain into tiny, claustrophobic pockets of dry rock, and suddenly everyone was stuck in the same elevator.

In the middle of this chaos, one single job took priority over food, sleep, and sanity: protecting the fire. Back then, starting a fire from scratch was an exhausting, blister-inducing chore. While hominids had been babysitting existing flames for hundreds of thousands of years at sites like Qesem Cave and Wonderwerk, sparking a fresh blaze with friction sticks was agonizingly unreliable. If your fire drowned, you couldn't just flick a plastic lighter. Tribes solved this by carrying smoldering embers wrapped in green leaves or packed inside woody tinder fungus. Tinder fungus is basically Mother Nature's biological lighter; it can slowly burn inside itself for hours without extinguishing. We know our ancestors treated fire like gold because when scientists thawed out Ötzi the Iceman - the five-thousand-year-old traveler frozen in the Alps - they found a dedicated survival fanny pack containing tinder fungus, flint, and iron pyrite sparks. When a monsoon hit, everyone sprang into action. They dragged the coals into the deepest recesses of the cave, erected hide windbreaks, gathered sheltered deadwood from underneath evergreen canopies, and peeled wet logs to harvest the dry heartwood. They also hoarded birch bark, which contains an oil called betulin that burns aggressively even when dripping wet. Guarding that single flame was a life-or-death vigil. If the fire died, you were freezing in the dark alongside hungry predators.

Once the fire was secured and everyone accepted that leaving was impossible, human nature took over. When modern humans get trapped indoors, they scroll social media until their eyes hurt. When ancient humans got trapped indoors, they invented modern technology. The archaeological record proves that rainy days were basically prehistoric hackathons. Caves are universally littered with manufacturing waste. Archaeologists find dense carpets of tiny rock chips clustered right beside fireplace hearths, showing where flintknappers sat under flickering torchlight for hours, mass-producing spearheads and scrapers. At Blombos Cave in South Africa, researchers uncovered a one-hundred-thousand-year-old cosmetics chemistry lab: abalone shells used as paint pots, ground ochre pigment, and bone stirring spatulas. Sixty-one thousand years ago, delicate bone sewing needles started showing up with microscopic drilled eyelets. You don't delicately drill the eye of a needle while sprinting away from a mastodon; you craft it when bad weather leaves you with hours of uninterrupted focus. At Abri du Maras in France, Neanderthals produced twisted fiber string over fifty thousand years ago. In Germany's Hohle Fels cave, archaeologists uncovered a thirty-five-thousand-year-old mammoth ivory tool with four spiral holes designed exclusively for twisting rope. Rope changed everything. It let humans lash shelter frames, tie stone blades onto wooden shafts, and build hunting snares. String is the unsung operating system of civilization, and it was almost certainly invented because someone was stuck in a cave waiting for the rain to stop.

They even upgraded their interior design. At Sibudu Cave in South Africa, excavators uncovered seventy-seven-thousand-year-old bedding woven from layers of marsh grasses and topped with aromatic Cape Laurel leaves. Cape Laurel happens to be a natural chemical insect repellent. Prehistoric people weren't just shivering on bare rock; they were crafting mosquito-resistant orthopedic mattresses. But the craziest rainy-day breakthrough was art. Deep inside Chauvet Cave in France, master artists thirty-six thousand years ago painted thundering herds of horses, stalking lions, and woolly rhinos with unbelievable skill. They understood shading, anatomical perspective, and movement so vividly that the beasts look alive. Similar masterpieces appear across Lascaux, Altamira, and Sulawesi in Indonesia, which houses figurative art dating back forty-five thousand years. Crucially, these paintings aren't located near the comfortable cave entrance where people hung out. They are hidden hundreds of meters deep in claustrophobic, pitch-black chambers that required crawling on your stomach with smoky animal fat lamps. Nobody crawls into an underground abyss to paint on a sunny afternoon when game is abundant. You venture into the subterranean dark when a storm has raged for three days, every spear has already been sharpened, and your creative brain is desperate for an outlet.

Rain didn't just forge tools and paintings; it built human culture. When thirty people are jammed into a tight shelter with nothing to do, conversation shifts. In 2014, anthropologist Polly Wiessner analyzed conversations among the Ju/'hoansi Bushmen in the Kalahari Desert. During the daylight grind, eighty percent of talk was mundane workplace logistics: who is hunting where, who borrowed whose arrows, and who ate the last melon. But around the evening campfire, over eighty percent of chatter transformed into comedy, heroic legends, ghost stories, and singing. The glow of the fire softened faces, dissolved tension, and turned a rainy cave into the original comedy club and lecture hall. Elders passed down critical survival intelligence: which berries are poisonous, where hidden springs flow during droughts, and how to track wounded game. It also birthed mythology. Every culture on Earth possesses ancient rain folklore, usually composed by people huddled together trying to explain the roaring thunder outside. In Australia, Aboriginal oral histories accurately describe sea level rise and coastal floods from seven thousand years ago, preserved word for word across hundreds of generations. Bad weather wasn't lost time; it was cultural transmission time.

And when the storm finally subsided, the world handed ancient hunters a golden ticket. Soaking rain softens the earth, creating pristine, high-definition animal tracks. In wet mud, you can tell exactly what creature walked past, how heavy it was, how fast it was galloping, and where it went. Fresh water collected in natural rock basins, which humans often carved deeper into permanent cisterns. Wild mushrooms exploded overnight, soaked soil made digging nutrient-packed tubers effortless, and warm rains triggered massive termite swarms. Swarming termites are an ultra-dense protein superfood that could be scooped up by the handful without expending weapons. So what did ancient humans do when it rained all week? Everything that mattered. They guarded the flame, engineered needles and rope, constructed pest-free mattresses, painted masterpieces deep underground, and bound the tribe together with unforgettable stories. Rain didn't slow them down; it gave them the quiet hours needed to invent the future. They didn't have Netflix, but they never got bored. When your survival depends on what your hands can craft by firelight, you don't get bored - you get brilliant. And that rainy-day brilliance is the reason humanity conquered the world."""
}

def clean_title_for_lookup(title: str) -> str:
    clean = re.sub(r"^\d+\s*-\s*", "", title)
    clean = re.sub(r"[#\\*?]", "", clean)
    clean = re.sub(r"[^a-zA-Z0-9\s]", "", clean).strip().lower()
    return clean

def get_spun_script_for_title(title: str, raw_transcript: str = "") -> str:
    """
    Retrieve witty spun script. If matches known reference video, returns high-retention spun master.
    Otherwise applies sentence-level rephrasing transformations.
    """
    norm_title = clean_title_for_lookup(title)
    for ref_name, script in REFERENCE_SPUN_SCRIPTS.items():
        if clean_title_for_lookup(ref_name) in norm_title or norm_title in clean_title_for_lookup(ref_name):
            return script.strip()

    if raw_transcript:
        return spin_transcript_sentences(raw_transcript)

    return ""

def spin_transcript_sentences(raw_text: str) -> str:
    """
    Fallback sentence-level rewriting transformation.
    Applies humorous mutations, synonym variations, active-voice shifts,
    and conversational cadence so that text is never an exact duplicate.
    """
    replacements = [
        (r"\bTonight, when the sun goes down\b", "Later tonight, as twilight falls"),
        (r"\byou're going to flip a switch\b", "you're going to flick a plastic wall switch"),
        (r"\bLight will flood the room\b", "Instant artificial sun will flood the room"),
        (r"\band you won't think twice about it\b", "without giving it a second thought"),
        (r"\bBut for 99\.9% of human history\b", "Yet across ninety-nine point nine percent of human history"),
        (r"\bthat switch didn't exist\b", "that little switch simply didn't exist"),
        (r"\bWhen the sun set, the world went dark\b", "When the sun dropped, the planet turned into a giant sensory deprivation chamber"),
        (r"\bYou couldn't even see your own hand in front of your face\b", "You couldn't see your own hand in front of your face, let alone your feet"),
        (r"\bFor over 300,000 years\b", "For more than three hundred thousand years"),
        (r"\bevery single one of your ancestors\b", "every single generation of your ancestors"),
        (r"\bLet's start with fire\b", "To understand this, we have to talk about fire"),
        (r"\bThis is not an exaggeration\b", "This is zero exaggeration"),
        (r"\bThink about this\b", "Consider the mathematics of this"),
        (r"\bWiessner argued that\b", "Wiessner realized that"),
        (r"\bIt's where we became us\b", "It's where human culture was officially born"),
        (r"\bYou were not designed to sleep the way you sleep right now\b", "Turns out, your body was never actually designed for an eight-hour sleep marathon"),
        (r"\bThis wasn't insomnia\. This was normal\b", "This wasn't insomnia. It was just Tuesday"),
        (r"\bWhat if it's not a disorder at all\b", "What if waking up at 3 AM isn't a medical glitch at all"),
        (r"\bWe traded all of that for a light switch\b", "We traded that entire cosmic connection for an electric light switch")
    ]

    spun = raw_text
    for pat, rep in replacements:
        spun = re.sub(pat, rep, spun, flags=re.IGNORECASE)

    return spun
